### ISSUE TITLE
Seems that Msg_task_set_affinity() doesn't work

### ISSUE THREAD

**Issue by kenenbek** [simgrid/simgrid#101]
I tried to use _**Msg_task_set_affinity()**_, but simgrid gives an error. I posted a question on [stackoverflow](http://stackoverflow.com/questions/38597387/how-properly-use-affinity-in-simgid).

The example from [example/msg/cloud-multicore/cloud-multicore.c](https://github.com/simgrid/simgrid/blob/master/examples/msg/cloud-multicore/cloud-multicore.c) also raises the same exception.

**Comment by mquinson** [comment]
Hello,

I think that we will soon remove that function all together. See #104.
