### ISSUE TITLE
Seems that Msg_file_rcopy() doesn't work

### ISSUE THREAD

**Issue by kenenbek** [simgrid/simgrid#102]
Hello.
Seems that Msg_file_rcopy() doesn't work when host tries to spawn  processes  which will use Msg_file_rcopy(), in other words host (maybe?) unable to copy file into three remote location in the same time (copying into 1 place is OK). 
MWE is here https://github.com/kenenbek/sss

**Comment by frs69wq** [comment]
I tested your code, and if you remove the division by INMEGA in your XBT_INFO you'll see that the used size of disk1 goes from 13204978 Bytes to 13300621. This makes 95643 bytes which corresponds to 3*31881, the size of the copied file. So what's the issue there?

**Comment by kenenbek** [comment]
Do you want to say that code from https://github.com/kenenbek/sss is working without segmentation fault?

**Comment by frs69wq** [comment]
well yes ... The only thing I changed is to remove the first line in CMakeLists.txt.

/tmp/sss$ ./Storage remote_io.xml io-remote_d.xml 
[0.000000] [remote_io/INFO] Init: 13204978 MiB used on 'Disk1'
[0.000000] [remote_io/INFO] Init: 835545 MiB used on 'Disk2'
[dave:copy1:(3) 0.000000] [remote_io/INFO] Copy 'c:\Windows\Professional.xml' (of size 31881) from 'dave' to 'carl'
[dave:copy2:(4) 0.000000] [remote_io/INFO] Copy 'c:\Windows\Professional.xml' (of size 31881) from 'dave' to 'carl'
[dave:copy3:(5) 0.000000] [remote_io/INFO] Copy 'c:\Windows\Professional.xml' (of size 31881) from 'dave' to 'carl'
[0.004061] [remote_io/INFO] Init: 13300621 MiB used on 'Disk1'
[0.004061] [remote_io/INFO] Init: 835545 MiB used on 'Disk2'
[0.004061] [remote_io/INFO] Simulation time 0.00406098

**Comment by frs69wq** [comment]
However, I just make a make install of my Simgrid installation and now I see your issue ...

**Comment by kenenbek** [comment]
What was the version of simgrid when code run fine?
Does this can cause the problem? :
Warning: Your program was compiled with SimGrid version 3.13.90, and then linked against SimGrid 3.13.0. Proceeding anyway.

**Comment by mquinson** [comment]
This is very dangerous to compile your code against 3.13.90 (ie, 3.14 beta) and then link it against 3.13. 

You should run ```ldd yoursimulator``` to see where it gets the dynamic library from, and make sure that that's a 3.13.90 dynamic lib. You can try to remove the 3.13 dynamic libs for that.

**Comment by frs69wq** [comment]
The issue was caused by a recent modification about how arguments passed to a process at creation are handled. Here process "host" spawns 3 "create_copy" processes that use a soft copy of the content of "host"'s argv. This process ends right after the spawn, freeing its argv, which leads to to invalid memory accesses within the spawned processes. A satisfactory correction has been proposed in https://github.com/kenenbek/sss/pull/1 
This closes this issue.
