### ISSUE TITLE
Multicore model could be simplified and otherwise improved

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#104]
Hello,

the way we currently model multi-core hosts is not very practical and should be redone. I am opening this issue to discuss how a better model could be achieved. Please comment.

## Current system

A CPU containing 8 cores of 1Gflop each is represented by 9 constraints in the LMM. The main constraint is bounded at 8 * 1 Gflop while each of the 8 other constraints are bounded at 1 Gflop. When you schedule a task on the CPU, it is only expended in the main constraint, resulting in a limitation of 8*1 Gflop. 

You can play with the uneasy setAffinity to pin your task on a given constraint, but you don't have to because afterward the variable representing the task is manually limited to 1Gflop (here: https://github.com/simgrid/simgrid/blob/master/src/surf/cpu_cas01.cpp#L183). This limitation to the task is updated when the speed of the CPU changes (here: https://github.com/simgrid/simgrid/blob/master/src/surf/cpu_cas01.cpp#L126).

So, you get the expected timings. I just ran some tasks of size 1000 on a 4-cores CPU of speed 1000, and as long as less than 4 tasks are running, each of them take exactly one second. 

## But gosh, this is ugly.

I don't like the fact that the one-core bound is carried by the variable itself instead of an extra constraint. I see that as a error in the concern separation. Task migration would be very cluttered, for example. We have to update each task/variable when a CPU/constraint's speed is updated. If the CPU is updated, why do I have to modify each task? Because I messed up the separation because CPU's and task's concerns!

I don't like the setAffinity API, even if this is exactly the one used in libVirt. We are not at the same level of abstraction, and this API seems error prone to me. It seems to me that in reality you pin a task to a core to reduce the amount of context switches and of cache misses, while this representation in SimGrid seem to imply that a task pinned on a given core will get its whole core. Remember, it's all about sharing in a fluid model in SimGrid, and there is no cache miss nor context switch delays.

This model is more detailed and thus seemingly preferable, but it's not practical,  there is no real reason for this to be accurate and it's probably deceiving to most of our users' hopes and understanding.

## Proposed model

We create only 2 constraints per CPU. For a 8-cores CPU of 1Gflop, we have:

- a 8*1 Gflop constraint representing the maximal amount available to all tasks
- a 1 Gflop constraint in the mode called FATPIPE where there is no sharing (the consumption of one task does not impact the availability of another task). This represents the one-core bound that is currently carried by each and every variable/task..

Each task would be binded to both constraints, resulting in a less surprising result for our users, for a less cluttered code. 

We would loose the setAffinity() API but I really doubt that is was ever wisely used by our users. To do that properly, I'd prefer to allow the user to define new constraints to the LMM in some sense, even if I'm not sure of how to do that yet.

**Comment by alegrand** [comment]
Actually, the model I wrote years ago for multicore was the one you propose. It was even simpler as it used only one constraint, the 8*1 Gflop and a 1Gflop bound per task to reduce the load on lmm. Pinning was not possible and I guess some people wanted it so it has been introduced in this uggly way but I have to say I'm not a big fan either. My feeling is that this (one-contraint) core model is the simplest one and that if people want to go into something more detailed with more control, they should model the cores as hosts, in a manual way. It was a burden years ago as we only add rigid xml description. But with the more flexible lua approach, this becomes quite easy to do...

**Comment by alebre** [comment]
One point that I do not understand with your proposal regards the way you guarantee that one task is not going to receive more than the CPU power provided by one core (i.e. 1Gflop in your instance). Moreover, how can you manage the sharing situation when you will have more tasks than the number of cores (and thus, you will have few tasks that must share the same core). I'm not sure whether this situation should be considered because it tries to model really low levels (maybe a global constraint such as the one that is already present is good enough). 

PS: Actually, I would rather propose to remove the setAffinity issue/challenge from the discussion first and discuss what is the best way to model a multicore node a the LMM model.

**Comment by alegrand** [comment]
Well, if setAffinity is out of the loop, then 1 contraint + 1 bound per task will allow to have 9 tasks running at 8/9Gflops in a trivial way whereas with 8+1 constraints, it would just not be possible, one of the 9 tasks would always be sacrified.

**Comment by alebre** [comment]
''will allow to have 9 tasks running at XXX'''  XXX is the important part of your message. You have only 8Gflops not 9... This is the point I don't understand for the moment. 
In the 8+1 constraints approach, if you have 9 tasks, you can map one task on the seven first cores and then two tasks on the last one for instance. Did I miss something ?

**Comment by frs69wq** [comment]
what about unbalanced computations on cores? 

Here is a simple scenario one might want to simulate:
a 4-core host at 1Gf per core and 5 tasks. 3 tasks compute 4Gf the 2 others  only 2. If I pin the small tasks on the same core, they will share its capacity, while the 3 others (also pinned) have the full capacity of a core each. Then all the task should end at time 4.

I think that in your proposal, each will get 4/5 Gf each. the small tasks will then end at time 2.5. After that the 3 remaining will have the full speed to end at 4.5

**Comment by alebre** [comment]
I agree with frs69wq. However from my point of view the issue occurs even without considering the pinning feature.

**Comment by alegrand** [comment]
As far as I understood, there are three models (and all use the 1Gflop
bound per action to ensure they never exceed the capacity of a core):

- 1 constraint. mapping 9 tasks will lead to (.88, .88, .88,
  ...., .88).
- 8 constraints model: mapping 9 tasks will lead to
  (1,1, ..., 1, .5,.5) and the user has to decide which tasks are
  colocated.
- 8+1 constraints, which is a union of the previous two ones: where
  both behavior can be obtained depending whether the pinning is done
  or not. I tried to come up with situations where the sharing would
  be really weird and unexpected (e.g., if only a few tasks are
  pinned) but I failed so everything seems all right.

@frs69wq: it seems that the example you give simply advocates for
keeping the pinning API. Am I right ? 

Now, it seems to me that if Martin's goal is to simplify this code, the
simplest is to have the 1 constraint model by default and to allow
pinning through an explicit modeling of cores in the platform
(remember in lua, we can simply replace the function that would create
a host by a function that would create 8 hosts within a small AS).

**Comment by mquinson** [comment]
Ok, sorry for the delay.

@alegrand gave the argument for the ugliness of bounding the variable/task instead of introducing a nice new constraint for that 1-core bound: reduce the load on the LMM. I'm not sure I understand how bounds on variables can be achieved more efficiently than a regular constraint, but I'm sure there is a cleavugly trick for that deep below :)
I will document that fact and make a step aside from my quest for code clarity. Don't take it as an habit ;) 

So, I think that this is the setAffinity() that will taste my blade. @alebre, who first introduced it, does not seem too attached to it, and it complicates the code in some places. We should document (or provide an example) on how to do what @alegrand advises, and we'd be good, wouldn't we?

Thanks for your time,

**Comment by alebre** [comment]
After giving a short look on the surf code (and unless I am mistaken), I saw that : 
-  the VM code does not use the affinity capability (the code is present but it is not used directly). 
-  the code comes from the action's related one (and thus, I'm not sure I was the one that introduced the affinity capability :-P)

regarding the one constraint model ( "1 constraint. mapping 9 tasks will lead to (.88, .88, .88, ...., .88).") not sure it is correct maybe it is good enough but not representative to the reality.

**Comment by mquinson** [comment]
Actually, my question was more on if you are using setAffinity() in your own code, out of the SimGrid code base. In could have grepped simgrid myself, but not VMPlaceS.

**Comment by alebre** [comment]
so the answer is no .

**Comment by mquinson** [comment]
Then I think I will remove the setAffinity API and document how to model a multicore machine. @alegrand, do you have a relevant platform file at hand, maybe?

**Comment by mquinson** [comment]
Ok, I created a new section in the doc to gather modeling tips and tricks, and then I added a section "how to model multicores" in there. That's here (in case you want to develop/change it):  https://github.com/simgrid/simgrid/blob/master/doc/doxygen/howtos.doc#L21

Now, I will kill the setAffinity() feature and everything related to simplify the codebase.

Unless somebody objects (in, say, the next hour ;)

**Comment by mquinson** [comment]
This is done in e5a5b0f6ee35cb592f9345a9dafa0e29df8477ef, thus closing.
