### ISSUE TITLE
Shutdown/destroy a VM during a migration 

### ISSUE THREAD

**Issue by alebre** [simgrid/simgrid#105]
It would be nice to have an exception that can occur in the migration code when someone tries to shutdown/destroy the VM. For the moment, the behaviour is the opposite: You cannot shutdown/destroy a VM if the VM is migrating. Because the migration process can last a significant amount of time, this is rather critical and not representative to what administrators can do :(

**Comment by mquinson** [comment]
Could you please setup a minimal example representing what you would like to get? It'd help me to implement it.
Thx.

**Comment by alebre** [comment]
* Two hosts: H0 and H1
* one VM: VM0 with a dirty page of 90% 
* VM0 is created and started on H0
* A process will be attached to VM0 and run a task to heavily stress the CPU (by such a mean, ie. the CPU stress and a high dirty page rate, I'm sure that the migration will last a significiant amount of time, long enough to perform the shutdown of H0.
* VM0 is migrated between H0 and H1 in an asynchronous manner (i.e. within another process on H0)
* after let's say 2 seconds, someone shutdown the VM.

Right now, you will get an error that will notify you that there is an ongoing migration. 
This is rather bad because if the migration last let's say 120 seconds, you cannot stop the VM before the end of the migration.
It will be great to raise an exception that can be caught at the level of the migration code. 
By catching the exception the migration code can return and the VM can be directly stopped as expected.

Hoping it helps
