### ISSUE TITLE
Unable to launch on OS X: 'no main manifest attribute, in simgrid.jar'

### ISSUE THREAD

**Issue by virl** [simgrid/simgrid#109]
When trying to launch in OS X via `java -jar simgrid.jar`:
```
no main manifest attribute, in simgrid.jar
```
java -version:
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

The cause most probably is that META-INF/MANIFEST.MF doesn't contain Main-Class string: http://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute

**Comment by adegomme** [comment]
Hi,
Any specific reason for closing this issue just after having opened it ? Which version of OS X is involved ?

**Comment by virl** [comment]
@adegomme 
I'm closed the issue because as I understand now simgrid.jar is just a Java library, not a UI app with Main class. Am I correct?

OS X El Capitan 10.11.6

**Comment by adegomme** [comment]
Indeed, you have to run a simulation with a main, using simgrid as a library. Some examples can be found in examples/java, and you can find more information on the usage here : http://simgrid.gforge.inria.fr/simgrid/latest/doc/bindings.html

**Comment by virl** [comment]
@adegomme Thank you!
