### ISSUE TITLE
How to change the loopback link characteristics?

### ISSUE THREAD

**Issue by aliomarabdelazim** [simgrid/simgrid#111]
Hello, 
I am trying to simulate multicore system, so I am trying to understand how "cores" works in SimDag, I created a system with 10 hosts each host has different number of cores, but when I schedule two tasks on a multicore host, the tasks share the host processing speed as if it was single core machine.
Another question regarding communication between cores on same host, I could not find any information on what is the speed of communication between cores, what is it model ? how can I modify this speed to model a system? 

I attached the code to expose both my questions (tasks share host speed even though there are idle cores and the communication speed between cores) 
to run just type ./simulator platform.xml 4 4

Thanks in advance 
[multicore_scheduling.zip](https://github.com/simgrid/simgrid/files/442840/multicore_scheduling.zip)

**Comment by mquinson** [comment]
Hello,

the following page may help you to understand our vision of multicores: http://simgrid.gforge.inria.fr/simgrid/3.13.90/doc/howto.html (there is a dedicated section, but the whole page may be interesting)

As for the communication between one host and itself, it seems rather hardcoded to me:
```
src/surf/network_cm02.cpp:  routing_model_create(createLink("__loopback__", 498000000, 0.000015, SURF_LINK_FATPIPE, nullptr));
```

So that's a 500GB/s link that is not shared (each user can get the max capacity), with a 15us delay. I can't believe that nobody ever wanted to change this value so far, but it seems so. I'll have to investigate it a bit more tomorrow.

**Comment by aliomarabdelazim** [comment]
Thank you very much for the fast reply,
“ If you put one activity of 8 GFlop on this host, it will be computed in 1 second (by default, activities are single-threaded and cannot leverage the computing power of more than one core). If you put two of them together, they will still be computed in one second, and so on up to 4 tasks.”
I have already read this before, the problem is I do not get this behavior from SimDag with the attached code, even though the first host is 3 cores in my example, when I schedule 2 tasks on it, they share a single core speed as if it was a single core host (the speed get divided into 2 when I schedule two tasks, and divided into 3 when I schedule 3 tasks)

Best regards,
Ali



On 29 Aug 2016, at 22:43, Martin Quinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

the following page may help you to understand our vision of multicores: http://simgrid.gforge.inria.fr/simgrid/3.13.90/doc/howto.html (there is a dedicated section, but the whole page may be interesting)

As for the communication between one host and itself, it seems rather hardcoded to me:

src/surf/network_cm02.cpp:  routing_model_create(createLink("__loopback__", 498000000, 0.000015, SURF_LINK_FATPIPE, nullptr));


So that's a 500GB/s link that is not shared (each user can get the max capacity), with a 15us delay. I can't believe that nobody ever wanted to change this value so far, but it seems so. I'll have to investigate it a bit more tomorrow.

**Comment by frs69wq** [comment]
Hi

I'm not sure that multi core hosts are handled the same way with the ptask_L07 model used by default by simdag. If you don't use parallel tasks but only typed ones (comp_seq and comm_e2e), I would advice to fall back to the "regular" model compound (cas01 for computing and clm02 for communications, I think). There should be some documentation about changing models on command line, but as I'm away from my computer, I can't give you the link to it. Maybe someone on the list can do that.

F.

**Comment by aliomarabdelazim** [comment]
thank you very much Frederic Suter, it now works with the compound host model, still need to know whether it is possible to change the parameters for the communication between cores or not

**Comment by mquinson** [comment]
@frs69wq @alegrand and others, I need help here. I must confess that I have no idea of how to change the characteristics of the loopback link. Do you have a trick about it?

**Comment by mquinson** [comment]
Hello,

I found an easy way to specify the loopback link: you just have to specify a route from each host to itself, since the existing models add a loopback only if none is specified in the platform. 

I will add this to the documentation before closing that bug.

Mt

**Comment by aliomarabdelazim** [comment]
Great, I did not try this before. Thank you very much for your answer.
