### ISSUE TITLE
platform cluster/host order

### ISSUE THREAD

**Issue by qazxiaye** [simgrid/simgrid#117]
Hello,

I find something strange that the position of cluster in a platform file does matters. 

I've got an error msg when I have :
host1
host2
cluster1

But it works when I modify it to be :
host1
cluster1
host2

Here is my platform with error : [https://drive.google.com/open?id=0B5mDEdbPR6y3RXZTc3hUMHlkV00](https://drive.google.com/open?id=0B5mDEdbPR6y3RXZTc3hUMHlkV00)

Here is the modified platform : [https://drive.google.com/open?id=0B5mDEdbPR6y3bE9CQzZmbkp5am8](https://drive.google.com/open?id=0B5mDEdbPR6y3bE9CQzZmbkp5am8)

The only difference is that line 9 and line 10 are reordered.

Thanks.

**Comment by mquinson** [comment]
Hello,

as with #116 and #296, the problem comes from the fact that you are mixing host and clusters in the same zone. This should not be allowed, and the parse now correctly reports the error. Thus closing.

Thanks for reporting, and sorry for the delay,
Mt.
