### ISSUE TITLE
Your SonarQube token is compromised

### ISSUE THREAD

**Issue by Godin** [simgrid/simgrid#127]
Because of usage of `set -x` your SonarQube token is presented in Travis logs.

**Comment by mquinson** [comment]
I'm so stupid :-( 
Thanks for noticing, I will regenerate it.

**Comment by Godin** [comment]
@mquinson I hope you'll fix root cause before regeneration? Otherwise I guess SonarSource guys maintaining SonarQube.com will revoke it again ;)

**Comment by mquinson** [comment]
Since someone was triggering travis build during my operation, I'm not absolutely sure that the new one was not compromised too... Let me check.

**Comment by mquinson** [comment]
nope, it seems to be OK. Only the old "ac......." was exposed, not the new one I just generated.
