### ISSUE TITLE
3.14: MSG_process_attach crashes

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#130]
With simgrid 3.14 we start using MSG_process_attach, but it seems to crash:

(gdb) bt
#0  0x00007fa1ab7e81a6 in simgrid::simix::marshal<std::function<void ()> const*>(s_smx_simcall*, e_smx_simcall_t, std::function<void ()> const* const&) (simcall=0xb0, call=SIMCALL_RUN_KERNEL, a#0=@0x7ffd9e1ec6c8: 0x7ffd9e1ec720)
    at /tmp/SimGrid-3.14.159/src/simix/popping_private.h:164
#1  0x00007fa1ab7e5984 in simcall<void, const std::function<void()>*>(e_smx_simcall_t, const std::function<void()> * const&) (call=SIMCALL_RUN_KERNEL, t#0=@0x7ffd9e1ec6c8: 0x7ffd9e1ec720)
    at /tmp/SimGrid-3.14.159/src/simix/popping_bodies.cpp:27
#2  0x00007fa1ab7df699 in simcall_BODY_run_kernel(const std::function<void()> *) (code=0x7ffd9e1ec720)
    at /tmp/SimGrid-3.14.159/src/simix/popping_bodies.cpp:401
#3  0x00007fa1ab7e16b5 in simcall_run_kernel(std::function<void ()> const&) (code=...)
    at /tmp/SimGrid-3.14.159/src/simix/libsmx.cpp:826
#4  0x00007fa1ab7b76b1 in simgrid::simix::kernelImmediate<simgrid::s4u::Host::setProperty(char const*, char const*)::<lambda()> >(<unknown type in /usr/local/lib/libsimgrid.so.3.14.159, CU 0x11110d, DIE 0x13e8f6>) (
    code=<unknown type in /usr/local/lib/libsimgrid.so.3.14.159, CU 0x11110d, DIE 0x13e8f6>)
    at /tmp/SimGrid-3.14.159/include/simgrid/simix.hpp:71
#5  0x00007fa1ab7b6ec4 in simgrid::s4u::Host::setProperty (this=0x55fdcdc70340, key=0x55fdcdc702c0 "memsize", 
    value=0x55fdcdc6c3d0 "5636554752") at /tmp/SimGrid-3.14.159/src/s4u/s4u_host.cpp:176
#6  0x00007fa1ab85c256 in sg_platf_new_host (args=0x7ffd9e1ec8a0) at /tmp/SimGrid-3.14.159/src/surf/sg_platf.cpp:78
#7  0x00007fa1ab87c95b in ETag_surfxml_host () at /tmp/SimGrid-3.14.159/src/surf/xml/surfxml_sax_cb.cpp:510
#8  0x00007fa1ab872db1 in surf_parse_lex () at /tmp/SimGrid-3.14.159/src/surf/xml/simgrid_dtd.c:7008
#9  0x00007fa1ab87f50a in _surf_parse () at /tmp/SimGrid-3.14.159/src/surf/xml/surfxml_sax_cb.cpp:1047
#10 0x00007fa1ab87ff5b in parse_platform_file (
    file=0x7ffd9e1ecb50 "/home/samy/.starpu/sampling//bus/mirage.platform.v4.xml")
    at /tmp/SimGrid-3.14.159/src/surf/xml/surfxml_parseplatf.cpp:178
#11 0x00007fa1ab7f002d in SIMIX_create_environment (
    file=0x7ffd9e1ecb50 "/home/samy/.starpu/sampling//bus/mirage.platform.v4.xml")
    at /tmp/SimGrid-3.14.159/src/simix/smx_environment.cpp:39
#12 0x00007fa1ab79b412 in MSG_create_environment (
    file=0x7ffd9e1ecb50 "/home/samy/.starpu/sampling//bus/mirage.platform.v4.xml")
    at /tmp/SimGrid-3.14.159/src/msg/msg_environment.cpp:34
#13 0x00007fa1abce4596 in start_simgrid (argc=<optimized out>, argv=0x7ffd9e1ed3a8) at ../../src/core/simgrid.c:219
#14 0x00007fa1abce4dc2 in _starpu_simgrid_init (argc=argc@entry=0x7ffd9e1ecf6c, argv=0x7ffd9e1ecf60)
    at ../../src/core/simgrid.c:280
#15 0x00007fa1abcc5671 in starpu_initialize (user_conf=0x0, argc=0x7ffd9e1ecf6c, argv=<optimized out>)
    at ../../src/core/workers.c:1091
#16 0x000055fdcd480176 in starpu_main (argc=<optimized out>, argv=<optimized out>)
    at ../../tests/datawizard/locality.c:98
#17 0x00007fa1aab322b1 in __libc_start_main (main=0x55fdcd47fe80 <main>, argc=1, argv=0x7ffd9e1ed3a8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd9e1ed398)
    at ../csu/libc-start.c:291
#18 0x000055fdcd47feba in _start ()

This should be reproducible with:

svn co -r 19630 svn://scm.gforge.inria.fr/svn/starpu/branches/starpu-1.2
cd starpu-1.2
./autogen.sh
./configure --enable-simgrid --disable-cuda --disable-opencl
make -j 12 -C src && make -j 12 -C tests
STARPU_PERF_MODEL_DIR=$PWD/tools/perfmodels/sampling STARPU_HOSTNAME=mirage ./tests/datawizard/simgrid-locality

**Comment by mquinson** [comment]
Mmm, this does not look good. I'll try to have a closer look soonish.

**Comment by mquinson** [comment]
hello @sthibaul, how did you solve this? Is it still crashing? Are you working around it in a satisfying way or do you still wait for us to fix it?

**Comment by sthibaul** [comment]
It seems it got fixed in simgrid 3.15
