### ISSUE TITLE
Java : a process can not shut down its own host

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#132]
Attached is an example showing that a process can not power off its own host in Java.

The following error is thrown : 
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 0.000000] /simgrid/src/xbt/exception.cpp:45: [xbt_exception/CRITICAL] Uncaught exception xbt_ex by energy VM runner/1: process cancelled

[SimGrid-BugReport-AutoPowerOff.zip](https://github.com/simgrid/simgrid/files/718874/SimGrid-BugReport-AutoPowerOff.zip)

**Comment by mquinson** [comment]
Hello,

I seem to understand that ProcessKilledError should be raised instead of HostFailure to keep consistant with C++, right? If so, this can be done with
```
jxbt_throw_by_name(env, "org/simgrid/msg/ProcessKilledError", "Host turned off");
```

**Comment by frs69wq** [comment]
the Host.off()method now throws a ProcessKilledError that has to be caught by the process when it turns down its own host.
 		try{
		  getHost().off();
		} catch (ProcessKilledError e) {
		  e.printStackTrace();
		}

**Comment by mquinson** [comment]
This is a very bad idea to catch ProcessKilledError, even more to survive it as advised... 

This is a maintenance exception, and you (really) should rethrow it after cleaning the stuff at this level. It is expected that actors surviving the ProcessKilledError lead to simulation segfaults, even in Java.

```Java
 try {
  getHost().off();
} catch (ProcessKilledError e) {
  e.printStackTrace();
  rethrow e;
}
```
