### ISSUE TITLE
Java : a process can run on a VM even if its host is off

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#133]
Attached is a minimal example showing that a process can run on a VM even if its host is off.

In this example, we design and run a process which print the following error message before exiting :
[vmHost_graphene-1.nancy.grid5000.fr:p1:(2) 18443.162598] /simgrid/src/bindings/java/jmsg.cpp:235: [jmsg/ERROR] I'm done, but you should not let me finish

As the process should not finish (because we shutdown its VM host), this message must not be thrown.
[SimGrid-BugReport-OnOffVM.zip](https://github.com/simgrid/simgrid/files/718896/SimGrid-BugReport-OnOffVM.zip)

**Comment by mquinson** [comment]
This seems to be fixed by b176f1f30ac1534c1e299bd01cfe35e4c517c084
