### ISSUE TITLE
Please bring back SD_route_get_{size,list}

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#138]
Hello,

We were using SD_route_get_size and SD_route_get_list to provide StarPU with the number of GPUs sharing a PCI link (information obtained from hwloc on a real machine), but commit 11667312f9c0886b8e7b6ca908266d33d2282b13 removed it, so StarPU can't be built against the current simgrid-git.

Samuel

**Comment by frs69wq** [comment]
Hi Sam, 
Sorry for the inconvenience, but these SimDag-specific functions have been moved to the more generic sg_* API and unfortunately changed in the process. However,his feature didn't completely disappear. It has been replaced by 
void sg_host_route(sg_host_t from, sg_host_t to, xbt_dynar_t links)
it allows you to get a dynar of all the links (which can be copied into an array with xbt_dynar_to_array()). Then you can retrieve the size of the route with xbt_dynar_length (or simply browse the dynar).

Would it be possible for you to adapt your code to use the new sg_host_route fonction? If not, I'll add some (temporary) backport functions.

F.

**Comment by sthibaul** [comment]
Ok, I have adapted my code.
