### ISSUE TITLE
Setting a breakpoint at a given time

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#143]
Hello,

I often see in my traces a point in time where something odd happens, and I'd like to get a gdb backtrace at that point, i.e. break when NOW >= given_time. Luka advised me to use "break SIMIX_process_yield if now >= given_time", but that's very very slow since gdb takes control back on each SIMIX_process_yield call.

It'd be useful that simgrid has an integrated option  for this, which would simply raise(SIGTRAP) when updating NOW if the new value is beyond the value passed to the option. Integration with the tracing tool would allow to e.g. just double-click on a point in time to get directly to the corresponding gdb backtrace :D

Samuel

**Comment by agiersch** [comment]
There's now a parameter --cfg=simix/breakpoint. Does it fill your needs?

**Comment by mquinson** [comment]
Hello,

I must confess that I dont love to have simix in the option name. But I cannot find any better name, unfortunately.

**Comment by sthibaul** [comment]
Hello,
That's exactly the idea, yes. For some reason it is however not working correctly for me. It does work with small values, but not for greater values. I'm however wondering: I see surf_solve always return something like 1E-5 in my tests, and the return in it (return time_delta) seems to imply that it returns the elapsed time, not an absolute date. I guess NOW should be used instead of time in the test time >= simgrid::simix::breakpoint ?

Samuel

**Comment by sthibaul** [comment]
MR !279 fixes the option for me.
