### ISSUE TITLE
MPI_TAG_UB attribute is small and bogus

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#146]
Hello,

smpi reports MPI_TAG_UB attribute as being 1000000 (as can be read in PMPI_Attr_get). That is a small value compared to the usual implementation values (2^31-1, typically), and applications often need more. Is there a reason for not just using 2^31-1?

**Comment by sthibaul** [comment]
Eerrr, worse, it seems the function does not work as expected at all:

`*static_cast<int**>(attr_value) = &tag_ub;`

AIUI, this puts the *address* of tag_ub instead of the value... It should rather be

`*static_cast<int*>(attr_value) = tag_ub;`

And similar for the other attr gets (MPI_HOST, IO, APPNUM, UNIVERSE_SIZE, LASTUSEDCODE, WTIME_IS_GLOBAL).

**Comment by adegomme** [comment]
I just pushed a fix for the first one, with a value of INT_MAX.

I don't think the second one is a bug, though.

The standard said :
The call to MPI_Attr_put passes in attribute_val the value of the attribute; the call to MPI_Attr_get passes in attribute_val the address of the the location where the attribute value is to be returned. Thus, if the attribute value itself is a pointer of type void*, the the actual attribute_val parameter to MPI_Attr_put will be of type void* and the actual attribute_val parameter to MPI_Attr_put will be of type void**. ( End of advice to users.) 

ps: attr_put and attr_get are deprecated, and replaced by comm_get_attr and comm_put_attr, but this shouldn't change much.. It's still a mess between fortran, new and old functions, though, so maybe our implementation is too naive for this.

**Comment by sthibaul** [comment]
The standard talks about the caller, not the callee: it explains to non-C experts that they have to provide the address of the variable to be filled with the value.

**Comment by sthibaul** [comment]
Errr, scratch that, let me check all of this again :)

**Comment by sthibaul** [comment]
Ok, sorry, it's indeed the application code I'm looking at which is bogus, and I wonder how it managed to work...
