### ISSUE TITLE
simgrid-mc not getting installed

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#148]
Hello,

I tried to build simgrid 3.15 with model-checking: 

cmake .. -Denable_model-checking=ON -DCMAKE_INSTALL_PREFIX=/tmp/foo && make -j 4 && make install

But simgrid-mc was not installed into /tmp/foo/bin/

**Comment by randomstuff** [comment]
Fixed in 59df3f3a606ec0942043c2f4b20e70d7c9d8a73f
