### ISSUE TITLE
Inconsistent event names in SMPI replay

### ISSUE THREAD

**Issue by rktesser** [simgrid/simgrid#150]
The event names in 'src/smpi/smpi_replay.cpp' are in camelCase while the ones in 'src/instr/instr_TI_trace.cpp' are all lowercase. This causes an out of range exception in 'src/xbt/xbt_replay.cpp:101', when it tries to get the function (action) that is associated to these events.

**Comment by mquinson** [comment]
Could you please detail a bit on how we can reproduce the bug, please? I'm a bit lost here...

**Comment by frs69wq** [comment]
Hi
Recent changes in the replay internals (move from xbt_str to boost mainly) induced a passage to lower case actions. I just forgot to look at the tracing part. 
This will be corrected soon.
Thx for reporting 

F.

**Comment by rktesser** [comment]
The tracing code is already in lowercase. It is the smpi replay code that is in camelcase. A previous version of the code solved this by converting event names to lowercase before inserting or retrieving actions (functions) from the dictionary.

To reproduce this you use smpirun to emulate an MPI code containing one or more calls corresponding to events in camelcase (e.g. MPI_Isend) and generate a time-independent trace. When you try to replay this trace, the event will not be found, so std::unordered_map will throw an out-of-bounds exception.

**Comment by frs69wq** [comment]
replay has entirely been rewritten in C++ by @Shruakai (d67d3ee is one of his last commits). This solves this issue, hence closing.
