### ISSUE TITLE
Call munmap with the correct size

### ISSUE THREAD

**Issue by Ezibenroc** [simgrid/simgrid#155]
[Curently](https://github.com/simgrid/simgrid/blob/6e25b005a8667e37e9010b4462dd3480ee4e577c/src/smpi/smpi_shared.cpp#L315) `munmap` is called with a size of 0. If the size is always stored in the metadata, we could use it.

**Comment by mquinson** [comment]
Could you please elaborate on where the size is stored? If you don't know that's OK, but I suspect that you do know, actually ;)

**Comment by Ezibenroc** [comment]
Fixed in #156, it seems the size is always correctly defined (well, the tests are still passing).
