### ISSUE TITLE
Dlopen privatization fails

### ISSUE THREAD

**Issue by Ezibenroc** [simgrid/simgrid#157]
This error happens with commits b382315f0693083344eb9a25a8fc37b7091bddc7 and 19c22f97fdb788225a64b0ca9aa64d9dee0ff865. It does not happen with commit 23a4a825789444c7bc954b0075fdd23715facaf5.

### MWE

This is the same MWE than #147, except for the `smpirun` arguments.

Check your simgrid version:
```bash
smpirun -git-version
# b382315f0693083344eb9a25a8fc37b7091bddc7
```

Get [HPL](https://github.com/simgrid/simgrid/files/885564/hpl.zip).

Then, run this:
```bash
# Unzip HPL
unzip hpl.zip
cd hpl

# Fix TOPdir variable
sed -ri "s|TOPdir\s*=.+|TOPdir="`pwd`"|g" Make.SMPI

# Compile HPL
make startup -j 8 arch=SMPI
make -j 8 arch=SMPI

# Run HPL
cd bin/SMPI
smpirun --cfg=smpi/bcast:mpich --cfg=smpi/running-power:6217956542.969 --cfg=smpi/display-timing:yes --cfg=smpi/privatize-global-variables:dlopen -np 16 -hostfile ./hostfile_64.txt -platform ./cluster_fat_tree_64.xml ./xhpl
```

It gives the following error:
```
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP-gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bcast' to 'mpich'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running-power' to '6217956542.969'
[0.000000] [xbt_cfg/INFO] Option smpi/running-power has been renamed to smpi/host-speed. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/display-timing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/privatize-global-variables' to 'dlopen'
[0.000000] [smpi_coll/INFO] Switch to algorithm mpich for collective bcast
[host-0.hawaii.edu:0:(1) 0.000000] /home/tom/Documents/simgrid/src/smpi/smpi_global.cpp:575: [root/CRITICAL] Cannot write into ./xhpl_9141_0.so
Backtrace (displayed in process 0):
---> xbt_backtrace_display_current at /home/tom/Documents/simgrid/src/xbt/backtrace.cpp:52, 0x7fa7736c69e2
---> operator() at /home/tom/Documents/simgrid/src/smpi/smpi_global.cpp:575, 0x7fa7736fe8b3
---> simgrid::kernel::context::RawContext::wrapper(void*) at /home/tom/Documents/simgrid/src/kernel/context/ContextRaw.cpp:304, 0x7fa7735e2962
./xhpl --cfg=smpi/privatize-global-variables:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI --cfg=network/TCP-gamma:4194304 --cfg=smpi/bcast:mpich --cfg=smpi/running-power:6217956542.969 --cfg=smpi/display-timing:yes --cfg=smpi/privatize-global-variables:dlopen ./cluster_fat_tree_64.xml smpitmp-appjfCdzV
Execution failed with code 134.
```

I also get a similar error with `NAS/ep`.

### Potential fix

The error happens in the `dlopen` privatization, when the library is copied.
My guess is that there misses a `O_CREAT` in the call to `open` [here](https://github.com/simgrid/simgrid/blob/19c22f97fdb788225a64b0ca9aa64d9dee0ff865/src/smpi/smpi_global.cpp#L574). We could also use `mkstemp`, since this file seems to be temporary.

I tried to fix it by replacing the call to `open` by this:
```c
int fdout = open(target_executable.c_str(), O_CREAT|O_RDWR, S_IRWXU);
```
Then, the call to `dlopen` fails, because one of the files is empty (I checked by removing the call to `unlink`).
Replacing the call to `sendfile` by this seems to fix the issue:
```c
off_t offset = 0;
sendfile(fdout, fdin, &offset, fdin_size);
```
I don't understand why though, since the file descriptor is private to each thread.

Also, I am not sure why this has not been caught by the tests. Am I missing something?

**Comment by mquinson** [comment]
Ahem. It seems that we don't have no tests for the dlopen feature right now... I will apply your fix as soon as we have a way to test that feature.

Thanks,
