### ISSUE TITLE
Stop unlinking the library copies in smpi_global.cpp ?

### ISSUE THREAD

**Issue by Ezibenroc** [simgrid/simgrid#160]
In [smpi_global.cpp](https://github.com/simgrid/simgrid/blob/master/src/smpi/smpi_global.cpp#L606) `unlink` is called for all copies of the library. I think the main reason is not to pollute your directory with tons of temporary files.

The downside is that it prevents [FlameGraph](https://github.com/brendangregg/FlameGraph) to working correctly. The script outputs one warnings like this per MPI process:
```
Failed to open /home/tom/hpl-2.2/bin/SMPI/xhpl_10821_4.so, continuing without symbols
```
Here is an example of output,  there are mainly two problems:
* There is one item `[xhpl...` per MPI process, they are not grouped.
* A lot of things are missing above the items `[xhpl...` (there are just some tiny columns that do not take all the width).

![flame_broken](https://cloud.githubusercontent.com/assets/8900834/25528296/61296042-2c1d-11e7-90e7-bf3b53314833.png)

If you remove the call to `unlink`, the warning messages disappear, and you get an output like this:

![flame_full](https://cloud.githubusercontent.com/assets/8900834/25528308/77312514-2c1d-11e7-8549-a58af209f72c.png)

You can see that it is much better.

Thus, I think there should be a way for the user to disable this call to `unlink` (without removing it by hand and recompiling simgrid). Maybe a command-line option? To be less annoying, these copies of the library could be made in `/tmp` instead of the current directory.

**Comment by randomstuff** [comment]
I guess debuggers are not quite happy about the missing files as well.

**Comment by randomstuff** [comment]
It would probably be a good idea to create all the temporary files in a per-simulation temporary directory and have `smpirun` remove it after the main program terminates.

**Comment by Ezibenroc** [comment]
> It would probably be a good idea to create all the temporary files in a per-simulation temporary directory and have smpirun remove it after the main program terminates.

In the case of flame graphs, you cannot remove the files immediately after the simulation, since the flame graph script has to be ran after:

```bash
smpirun -wrapper "perf record -F1000 --call-graph dwarf" --cfg=smpi/privatize-global-variables:dlopen -np 64 -hostfile ./hostfile_64.txt -platform ./cluster_fat_tree_64.xml ./xhpl

perf script | stackcollapse-perf.pl --kernel | flamegraph.pl > flame.svg # the files must still be available here
```

So the default behavior of `smpirun` should be to delete those files, except when an option `keep-library-files` is passed.

**Comment by randomstuff** [comment]
Yes indeed.
