### ISSUE TITLE
No more undefiend references are raised

### ISSUE THREAD

**Issue by Ezibenroc** [simgrid/simgrid#161]
Take this program, in a file `test.c`:
```c
int main(int argc, char *argv[]) {
    bla();
    return 0;
}
```

Compilation with `smpicc` prints a warning:
```
$ smpicc -O4 test.c -o test
/tmp/test.c: In function ‘main’:
/tmp/test.c:2:5: warning: implicit declaration of function ‘bla’ [-Wimplicit-function-declaration]
     bla();
     ^
$ echo $?
0
```
But the linker does not fail and the compilation succeeds, whereas it should obviously fail. You have to run the program to finally get an error.

**Comment by randomstuff** [comment]
Yes, indeed. This is a consequence of `smpicc` compiling the program as `--shared`.

**Comment by randomstuff** [comment]
The fix is apparently to pass `-z defs` to the linker (`-Wl,-z,defs`).

**Comment by randomstuff** [comment]
(in the `smpicc` script)
