### ISSUE TITLE
Avoid generic macro names

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#162]
Hello,

simgrid_config.h, included from simgrid/modelchecker.h, defines the HAVE_MC macro. This is a too generic name for a macro defined by a library, it should be prefixed  by at least XBT_, SIMGRID_, or something similar

Samuel

**Comment by mquinson** [comment]
I'm considering naming these macro SG_HAZ_MC or maybe more HAVE_MODELCHECKING. Less fun but less surprising too.

**Comment by sthibaul** [comment]
HAVE_MODELCHECKING still seems too generic. SG_something might be too short a prefix to be really "unique" too.

**Comment by mquinson** [comment]
SIMGRID_HAVE_MC, then?

**Comment by sthibaul** [comment]
yep, looks good :)
