### ISSUE TITLE
smpi_process_get_user_data disappeared

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#163]
Hello,

The prototype for smpi_process_get_user_data is still there in 3.15, but it seems the implementation is gone? We definitely need some per-thread data for StarPU...

Samuel

**Comment by sthibaul** [comment]
More generally, it's a pain for us to have per-thread data which is portable across both MSG and SMPI. We are currently using SIMIX_process_self_get_name() and running strtol over it to check whether it is an MPI rank... I'm not aware of any other way to determine whether a thread was created with SMPI vs MSG.

**Comment by alegrand** [comment]
FYI, Christian is currently fighting with process creation to allow a decent integration of MSG and SMPI process. The current implementation makes many assumptions on the creation order (MPI before MSG) and on the fact that the number of MPI process is known at the beginning of the simulation, which is a real pain. Distinguishing whether a process is an MPI one or not should be part of the picture. We discussed about it last Friday and I'll rediscuss about the implementation with him tomorrow.

**Comment by sthibaul** [comment]
Until this is fixed, could https://github.com/simgrid/simgrid/pull/164 be merged to restore these functions? ATM there is simply no released or git version that we can use for StarPU-Simgrid...

**Comment by mquinson** [comment]
Merged.
