### ISSUE TITLE
Issue in energy consumption calculation when powering off

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#171]
Hello,

There is a problem with the energy consumption calculation when powering off hosts (at least in the Java version of SimGrid). 

Attached is a minimal example describing this issue. In this example, we consider a single host with a static power consumption of 200W when ON and 8W when OFF. At time 0, when the host is ON, we (1) wait 10sec (2) switch OFF the host, and (3) check the energy consumed so far. The expected result is a consumption of 2000Joules because the host consumed 200W during 10sec. But the result I found is 80Joules, which correspond to the energy consumed by the host OFF during 10 sec.

If I check the consumed energy just before switching OFF the host (but still at the same simulation time of 10sec), then I have the expected consumption of 2000Joules.  It seems that powering off an host does not cause to update the energy consumption of the host. As a consequence, from an energy point of view, the host is considered OFF since the last energy consumption update.

Output of the example: 
time = 0.0 | host : adonis-10.grenoble.grid5000.fr | Power consumption : 0.0
time = 10.0 | host : adonis-10.grenoble.grid5000.fr | Power consumption : 80.0

Expected : 
time = 0.0 | host : adonis-10.grenoble.grid5000.fr | Power consumption : 0.0
time = 10.0 | host : adonis-10.grenoble.grid5000.fr | Power consumption : 2000.0

[SimGrid-BugReport-Energy-Calculation.zip](https://github.com/simgrid/simgrid/files/1026305/SimGrid-BugReport-Energy-Calculation.zip)

**Comment by mquinson** [comment]
According to https://github.com/simgrid/simgrid/blob/master/src/s4u/s4u_host.cpp#L102, the signal is fired after the state update, so you are damn right. The update is wrong of taking the current state to compute the consumption of previous stance, as done here: https://github.com/simgrid/simgrid/blob/master/src/surf/plugins/host_energy.cpp#L110

But the difficult part is that it seems to be the same issue for speed changes, which is supposed to be experimentally validated...

**Comment by mquinson** [comment]
Ok, I have a patch to solve this, but of course it invalidates all tests (since they were wrong). More to come.

**Comment by mquinson** [comment]
Actually, things are better than I thought. We already save the pstate from one call to another, and we only need to also save whether the host is on or  off. We cannot save the instantaneous consumption directly because we won't have the cpu_load  before the end of the time interval. 
I think I have a patch ready. I test and commit it.
