### ISSUE TITLE
JAVA: Cannot shutdown VM : it is not running

### ISSUE THREAD

**Issue by gossa** [simgrid/simgrid#172]
In Java, when the program ends, if a VM is shutted down but its ref are not released, you get a (probably) uncatchable exception "Cannot shutdown VM : it is not running"

It would be more handy if shutting down VM that are not running does not raise exception. A simple warning would be sufficient (even if I am not sure of the point).

[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:45: [xbt_exception/CRITICAL] Uncaught exception xbt_ex by maestro/0: Cannot shutdown VM myCloud-000_VM: it is not running
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> simgrid::xbt::backtrace() at /home/julien/repo/simgrid/src/xbt/backtrace.cpp:79, 0x7f263e729b2f
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> __base_ctor  at /home/julien/repo/simgrid/include/xbt/exception.hpp:85, 0x7f263e726b70
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> _xbt_throw at /home/julien/repo/simgrid/src/xbt/ex.cpp:65, 0x7f263e6f1856
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> simgrid::vm::VirtualMachineImpl::shutdown(simgrid::simix::ActorImpl*) at /home/julien/repo/simgrid/src/plugins/vm/VirtualMachineImpl.cpp:211, 0x7f263e63fd1f
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> simgrid::xbt::Result<decltype(nullptr)>::reset() at /home/julien/repo/simgrid/include/xbt/future.hpp:88, 0x7f263e66193d
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> SIMIX_simcall_handle at /home/julien/repo/simgrid/src/simix/popping_generated.cpp:355, 0x7f263e682cf5
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> SIMIX_run.part.105 at /home/julien/repo/simgrid/src/simix/smx_global.cpp:504, 0x7f263e70fe8e
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> SIMIX_run at /home/julien/repo/simgrid/src/simix/smx_global.cpp:568, 0x7f263e711265
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:54: [xbt_exception/CRITICAL]   -> MSG_main at /home/julien/repo/simgrid/src/msg/msg_global.cpp:89, 0x7f263e640487
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:80: [xbt_exception/CRITICAL] Current backtrace:
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> simgrid::xbt::backtrace() at /home/julien/repo/simgrid/src/xbt/backtrace.cpp:79, 0x7f263e729b2f
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> simgrid::xbt::handler() at /home/julien/repo/simgrid/src/xbt/exception.cpp:101, 0x7f263e6f0f78
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:?, 0x7f266b7656b6
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> std::terminate() at ??:?, 0x7f266b765701
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:?, 0x7f266b7656aa
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> simgrid::xbt::Result<decltype(nullptr)>::get() at /home/julien/repo/simgrid/include/xbt/future.hpp:139, 0x7f263e66468c
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> std::_Deque_iterator<simgrid::s4u::VirtualMachine*, simgrid::s4u::VirtualMachine*&, simgrid::s4u::VirtualMachine**>::_Deque_iterator(std::_Deque_iterator<simgrid::s4u::VirtualMachine*, simgrid::s4u::VirtualMachine*&, simgrid::s4u::VirtualMachine**> const&) at /usr/include/c++/5/bits/stl_deque.h:151, 0x7f263e3d2c97
[node-1.me:myCloud-ComputeEngine-Rice-Node-node-1.me:(27) 96224.170437] /home/julien/repo/simgrid/src/xbt/exception.cpp:82: [xbt_exception/CRITICAL]   -> ?? at [0x7f265501f9e4]

**Comment by mquinson** [comment]
Ok, I made this a XBT_VERB instead. So you won't see this unless you increase the default verbosity
