### ISSUE TITLE
all-in-one jarfile still broken on Mac OSX because of rpath

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#178]
When you try to use a simgrid.jar that was not compiled on your machine, you get an error stating that simgrid-java.dynlib cannot find simgrid.dynlib. This is because the simgrid library is searched in a directory which name is where they were built.

RPATH is somehow black Apple magic to me, but our RPATH settings seem pretty right to me. Simply, they are not taken into account because these libs are never formally installed by cmake, but rather copied directly from the source tree (see the end of `tools/cmake/Java.cmake`).

One possibility would be to have cmake doing a fake install, e.g. into NATIVE/ instead of copying, so that cmake does the right thing with rpath and friends. That would be really cool and robust in the long term if we find how to do that. 

Another possibility is to call `otool` ourselves on the copied library before packing the jarfile. It may be easier, but we have to understand what these commands are. 

# How to help

If you are a cmake dark wizard, please be my guest to try the first approach.
If you have access to a Mac, I'd appreciate if you could give a try to the second approach. Hello @bcamus @alebre @henricasanova  ;)

For that, take a simgrid.jar from [Jenkins](https://ci.inria.fr/simgrid/job/SimGrid-Multi/build_mode=Debug,node=simgrid-osx-mavericks/) (as an artifact at the top of this page), unpack it as a zipfile, play with otool as explained [here](https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath) and [there](https://cmake.org/Wiki/CMake_RPATH_handling#Mac_OS_X_and_the_RPATH), until `otool -L libsimgrid-java`does not show the full build path. Instead, you probably want to have `@loader_path` as a `@rpath`.

Once it's done, repack the jarfile with zip, and check whether it's now working for you.

Whether or not it works for you, please report in this issue what you did and what was the outcome, so that we can build upon your experience. Many thanks in advance.

**Comment by bcamus** [comment]
Ok, after numerous tests with the second approach, the following command seems to work for me:

 `install_name_tool -change /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.16/build/lib/libsimgrid.3.16.dylib @loader_path/libsimgrid.dylib libsimgrid-java.dylib `
