### ISSUE TITLE
simgrid::s4u::Engine::instance()->shutdown()   segfaults

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#185]
It seems that shutting down the instance leads to a segfault. This is important when trying to run Google tests on a SimGrid-based project, since that requires starting/shutting down instances in sequence.  

The attached mwe.zip highlights the bug ("make run").
[mwe.zip](https://github.com/simgrid/simgrid/files/1062221/mwe.zip)

**Comment by mquinson** [comment]
Hello,

you're asking for a feature that is cool but that is not exactly on our goal right now. You're asking for simgrid to become resetable. For now, we advice anyone to start a brand new OS process for a new simulation, and I think that making it optional is quite an amount of work, hunting for the dozens of global variables that we have all around the code.

This is definitly one of our goals on the long term but unfortunately, you probably want to find a workaround for the time being.

Sorry, Mt.

**Comment by henricasanova** [comment]
Hi,

thanks for the answer.  I get that it’s not a critical feature.  I’ll try to figure out how to tell the Google Test framework to fork a process instead of using a single process to run a sequence of tests….perhaps simply calling fork() in some clever fashion will work… 

thanks
Henri

**Comment by henricasanova** [comment]
oops, didn't mean to close this. Even though the "recycle the simulation" feature is out of reach for now, shutdown() should not segfault.
