### ISSUE TITLE
Energy consumption of parallel tasks

### ISSUE THREAD

**Issue by mpoquet** [simgrid/simgrid#189]
Hello,

I just found out that that hosts computing parallel tasks do not consume more energy than when they are idle. Is this behaviour desired? Are my platform and my code alright?

I used computation-only parallel tasks, which I thought would completely use the host computational resource.

MWE gist [there](https://gist.github.com/mpoquet/8dfcb26671415a5c4adec325381a3f8c) (short C++ file, platform XML file and a Makefile).

**Comment by mpoquet** [comment]
Patch with @shurakai:
``` patch
--- a/src/surf/plugins/host_energy.cpp
+++ b/src/surf/plugins/host_energy.cpp
@@ -207,8 +207,8 @@ double HostEnergy::getCurrentWattsValue(double cpu_load)
   double power_slope   = 0;
 
   if (cpu_load > 0) { /* Something is going on, the machine is not idle */
-    double min_power = range.min;
-    double max_power = range.max;
+    min_power = range.min;
+    max_power = range.max;
 
     /**
      * The min_power states how much we consume when only one single
@@ -220,15 +220,18 @@ double HostEnergy::getCurrentWattsValue(double cpu_load)
      * i.e., we need min_power + (maxCpuLoad-1/coreCount)*power_slope == max_power
      * (maxCpuLoad is by definition 1)
      */
-    double power_slope;
     int coreCount         = host->coreCount();
     double coreReciprocal = static_cast<double>(1) / static_cast<double>(coreCount);
     if (coreCount > 1)
+    {
       power_slope = (max_power - min_power) / (1 - coreReciprocal);
+      current_power = min_power + (cpu_load - coreReciprocal) * power_slope;
+    }
     else
-      power_slope = 0; // Should be 0, since max_power == min_power (in this case)
+    {
+      current_power = max_power;
+    }
 
-    current_power = min_power + (cpu_load - coreReciprocal) * power_slope;
   } else { /* Our machine is idle, take the dedicated value! */
     current_power = range.idle;
   }
```

**Comment by mpoquet** [comment]
Looks like the patch (commit e96681fb8) fixed the problem.

![energy_plot](https://user-images.githubusercontent.com/3502831/27192715-9f7191f8-51fc-11e7-8699-c828e76cef70.png)

**Comment by Shurakai** [comment]
I reverted my own patch in e3361464769385862476e0154a92370db824a607 and added an assert in 7cb96467cddc465b7b0f8f819755bc9c850198c5 since this is actually an error in the platform that needs to be fixed.

**Comment by mquinson** [comment]
Hello,

could you please tell us if the current version is fixing your problem? I reworked the patch of @Shurakai so that the misconfiguration is detected earlier in the process, and so that the provided examples show both mono-core and multi-cores hosts. Finally I gave an alternative configuration form for monocores.

See http://simgrid.gforge.inria.fr/simgrid/3.16/doc/group__SURF__plugin__energy.html for the current version of the doc.

**Comment by mpoquet** [comment]
Hello, thanks for the patch!

### Current status
It seems to work with the current SimGrid version (tested bee4b1233).
- If the platform is bad (Idle:MinSpeed:MaxSpeed), an assertion fails and shows a clear message
- using the "Idle:FullSpeed" syntax works
- using the "Idle:FullSpeed:FullSpeed" works too

### Problem
However, it seems that the behaviour described in the old energy 101 pdf has been lost when the cores have been introduced. I am mainly interested in coarse-grained simulation and I would like hosts who are not computing at full speed to use less power than 100%.

Two workloads are executed in the figure below. In the top one, computation-only jobs are used and should use 100% of the platform energy. In the second one, jobs use a mix of computation and communications and the network is saturated. Hence I expect the computing hosts to use less power, as in real life they would spend time waiting from the network and be idle for some time.

![energy_plot](https://user-images.githubusercontent.com/3502831/27395357-d29d607c-56af-11e7-8330-65632d2c7727.png)

But in both cases 100% of the host power is consumed :(.

### Model discussion
![20170620_152131](https://user-images.githubusercontent.com/3502831/27394655-3a7e8f5c-56ad-11e7-88be-841b3522273d.jpg)

It seems that the previous platform definition allowed to define:
- the idle power **pIDLE**
- the minimum power **p0** (when load is epsilon)
- the maximum power **pM**

The power of a host is then on the [**p0**, **pM**] segment depending on the host load.

Now, **p1** must be given instead of **p0** (**p1** is the power consumption when one core is loaded at 100%).
The problem is that **p0** cannot be retrieved for single-core hosts, since **p1** = **pM** in this case.
@alegrand proposes to use **p0**=**pIDLE** for single-core hosts. However, the power jump discontinuity from **pIDLE** to **p0** is lost in this case. It would be interesting to allow users to optionally specify **p0** (e.g. in a property), so that the jump phenomenon could still be simulated if needed.

What do you think about it?

**Comment by mquinson** [comment]
Of course I forgot about those damn ptasks when I rewrote the patch of @Shurakai, sorry...
 
If I get you right, you say that we should give 3 parameters to single cores, too, but with another meaning, right? **Idle:EpsilonLoad:FullLoad**. Ok, it works for me.

The main reason why I rewrote the patch is that it did not change the platform files, so they were no example of multicore energy instanciation. Now that we will change the single core case, could you please provide a typical instantiation that I could use as an example?

Thanks,

**Comment by mquinson** [comment]
Also, what should happen if we have 3 tasks taking 25% load on a quadri-core CPU? Will only one core be loaded at 75%, or will 3 cores be loaded at 25% ?

**Comment by mpoquet** [comment]
I'm ok with the **Idle:EpsilonLoad:FullLoad** syntax for single-core hosts.

### Platform example
This  platform uses single-core hosts with the **Idle:EpsilonLoad:FullLoad** syntax.
(The *sleep_pstates* property is Batsim sugar).
``` xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4.1">

<AS id="AS0" routing="Full">

    <cluster id="cluster_compute" prefix="host" suffix="" radical="0-31"
             bw="125MBps" lat="50us" bb_bw="2.25GBps" bb_lat="500us"
             speed="100.0Mf, 88.95899053627761Mf, 83.67952522255192Mf, 80.57142857142857Mf, 76.21621621621621Mf, 72.49357326478149Mf, 68.78048780487805Mf, 64.6788990825688Mf, 60.775862068965516Mf, 58.62785862785863Mf, 50.088809946714036Mf, 49.21465968586388Mf, 44.97607655502392Mf, 1e-9Mf, 0.1639344262295082f, 0.006599788806758183f">
        <!-- real pstates: 0 to 12
             off: pstate: 13
                  consumption: 9.75 W
             shutdown: pstate: 14
                       time: 6.1 s,
                       consumption: 100.99672131147543 W
             boot: pstate: 15
                   time: 151.52 s,
                   consumption: 125.1743848996832 W
        -->
        <prop id="watt_per_state" value="95.0:97.85000000000001:190.738, 95.0:97.85000000000001:171.02, 95.0:97.85000000000001:165.62, 95.0:97.85000000000001:160.47, 95.0:97.85000000000001:155.729, 95.0:97.85000000000001:151.3, 95.0:97.85000000000001:146.92, 95.0:97.85000000000001:142.95, 95.0:97.85000000000001:138.928, 95.0:97.85000000000001:135.368, 95.0:97.85000000000001:132.519, 95.0:97.85000000000001:128.87, 95.0:97.85000000000001:125.88, 9.75:9.75:9.75, 100.99672131147543:100.99672131147543:100.99672131147543, 125.1743848996832:125.1743848996832:125.1743848996832" />

        <prop id="watt_off" value="9.75" />

        <!-- OFF : ON->OFF (shutdown) : OFF->ON (booting) -->
        <prop id="sleep_pstates" value="13:14:15" />
    </cluster>

    <cluster id="cluster_master" prefix="master_host" suffix="" radical="0-0"
             bw="125MBps" lat="50us" bb_bw="2.25GBps" bb_lat="500us"
             speed="100.0Mf, 88.95899053627761Mf, 83.67952522255192Mf, 80.57142857142857Mf, 76.21621621621621Mf, 72.49357326478149Mf, 68.78048780487805Mf, 64.6788990825688Mf, 60.775862068965516Mf, 58.62785862785863Mf, 50.088809946714036Mf, 49.21465968586388Mf, 44.97607655502392Mf, 1e-9Mf, 0.1639344262295082f, 0.006599788806758183f">
        <!-- real pstates: 0 to 12
             off: pstate: 13
                  consumption: 9.75 W
             shutdown: pstate: 14
                       time: 6.1 s,
                       consumption: 100.99672131147543 W
             boot: pstate: 15
                   time: 151.52 s,
                   consumption: 125.1743848996832 W
        -->
        <prop id="watt_per_state" value="95.0:97.85000000000001:190.738, 95.0:97.85000000000001:171.02, 95.0:97.85000000000001:165.62, 95.0:97.85000000000001:160.47, 95.0:97.85000000000001:155.729, 95.0:97.85000000000001:151.3, 95.0:97.85000000000001:146.92, 95.0:97.85000000000001:142.95, 95.0:97.85000000000001:138.928, 95.0:97.85000000000001:135.368, 95.0:97.85000000000001:132.519, 95.0:97.85000000000001:128.87, 95.0:97.85000000000001:125.88, 9.75:9.75:9.75, 100.99672131147543:100.99672131147543:100.99672131147543, 125.1743848996832:125.1743848996832:125.1743848996832" />

        <prop id="watt_off" value="9.75" />

        <!-- OFF : ON->OFF (shutdown) : OFF->ON (booting) -->
        <prop id="sleep_pstates" value="13:14:15" />
    </cluster>

    <link id="backbone" bandwidth="1.25GBps" latency="500us" />

    <ASroute src="cluster_compute" dst="cluster_master" gw_src="hostcluster_compute_router"
        gw_dst="master_hostcluster_master_router">
        <link_ctn id="backbone" />
    </ASroute>
</AS>
</platform>
```

### Consumption of three 25% load tasks on a 4-core CPU
Mmh... I don't  know. In real life I think it would depend on the system scheduler, on the distribution of idle periods, on the CPU architecture and on the type of instructions used.

3 cores loaded at 25% seems fine to me as I focus on coarse-grained simulation.

For fine-grained simulation it depends on what we want to observe, as the consumption of complex CPUs might have other jump discontinuities depending on which cores are used for example.

As far as I understood the current model does not allow this kind of things, as the global load of the CPU is computed (**load** = sum of current computing speeds on the host / (nb_cores*host_max_speed)), and the consumption of the host is then **p0** + **slope** * **load** (or just **pIDLE** if the CPU is not doing anything):
- **slope** is derived from **p1** and **pM**
- **p0** is derived (intersection of the line coming from **slope** and **p1** and the load=0 vertical line)

In this case **p0** could be seen as the consumption of the CPU if all cores are at **EpsilonLoad**.

I think that if we want to observe low-level energy effects, finer-grained job representations that give more details about how the hosts are idle (e.g. SMPI) are more likely to be used than parallel tasks, so I think this is okay.

**Comment by mquinson** [comment]
I just discussed the issue with @alegrand and the best is to come up with a semantic that does not depend on the amount of core. So we will have `Idle:Full` regardless of the amount of cores, and we will do the linear interpolation to get the values. 

For the hardcore users wanting to differentiate between P_idle and P_0, we will allow to have `Idle:Epsilon:Full`. By default, Idle=Epsilon.

This is still to be done.

**Comment by mpoquet** [comment]
**Update**: The problem is still present with recent SimGrid versions.  
**Problem reminder**: Executing parallel tasks consume the Full host power regardless of the host load.

### Graphs with SimGrid 5256bf57 (2018-08-10)
Delays VS computation-only parallel task (expected load: 100 %)
![load0-100](https://user-images.githubusercontent.com/3502831/43994221-ae72bada-9d99-11e8-903b-7a05e0aa9c6f.png)

Delays VS parallel task saturated by network (expected load: 50 %)
![load0-50](https://user-images.githubusercontent.com/3502831/43994220-aaa48fd2-9d99-11e8-9087-ebc4b68724db.png)

### Reproduce
(Not tested, this is already a miracle that I could establish a TCP connection with github with this connection...)

``` bash
# Directories
export BATSIM_DIR=~/tmp/batsim
export EVALYS_DIR=~/tmp/evalys

###############
# Obtain data #
###############
# Retrieve Batsim
git clone https://framagit.org/batsim/batsim.git ${BATSIM_DIR}
cd ${BATSIM_DIR}
git checkout 1a5f224

# Build batsim
./ci/build.bash

# Run tests
./ci/run-tests.bash

#####################
# Visualize results #
#####################
# Retrieve evalys
git clone ??? ${EVALYS_DIR}
cd ${EVALYS_DIR}
git checkout 1b9435b

# Install evalys
pip install ${EVALYS_DIR} # root access may be needed depending on config

# Visualize empty (delays) and full (computation-only ptask) load
dir0=${BATSIM_DIR}/build/test-out/energy-minimal-energymini0
dir50=${BATSIM_DIR}/build/test-out/energy-minimal-energymini50
dir100=${BATSIM_DIR}/build/test-out/energy-minimal-energymini100

${EVALYS_DIR}/examples/poquetm/plot_energy_info.py \
    --gantt --power --energy \
    --off 13 \
    --switchoff 14 \
    --switchon 15 \
    --names load0 load100 \
    -j ${dir0}/out_jobs.csv \
       ${dir100}/out_jobs.csv \
    -p ${dir0}/out_pstate_changes.csv \
       ${dir100}/out_pstate_changes.csv \
    -e ${dir0}/out_consumed_energy.csv \
       ${dir100}/out_consumed_energy.csv \
    -o /tmp/load0-100.png

# Visualize empty (delays) and 50 % (mixed computation and communication) ptask
${EVALYS_DIR}/examples/poquetm/plot_energy_info.py \
    --gantt --power --energy \
    --off 13 \
    --switchoff 14 \
    --switchon 15 \
    --names load0 load50 \
    -j ${dir0}/out_jobs.csv \
       ${dir50}/out_jobs.csv \
    -p ${dir0}/out_pstate_changes.csv \
       ${dir50}/out_pstate_changes.csv \
    -e ${dir0}/out_consumed_energy.csv \
       ${dir50}/out_consumed_energy.csv \
    -o /tmp/load0-50.png
```

**Comment by Mommessc** [comment]
Hello,

Here is a recap of the model we discussed with @mpoquet this morning:

As proposed by @alegrand and @mquinson, the power values given for each power state are:
`P_Idle:P_Full` by default, where `P_Idle` is the power consumption when all cores are idle and `P_Full` is the power consumption when all cores are loaded at 100%.
An optional `P_Epsilon` can be given (with the syntax `P_Idle:P_Epsilon:P_Full`) that corresponds to a load of epsilon for all cores, i.e., to the classical `P_static` value.


As mentioned by mpoquet (provided the [lines 256 and 259](https://github.com/simgrid/simgrid/blob/master/src/plugins/host_energy.cpp#L256) are correct), the load of a host is currently computed as `the sum of current computing speeds / (nb_cores * host_max_speed)` and gives a value between 0 and 1.

The slope of the power consumption when the load is not integral is simply (replace `P_Epsilon` by `P_Idle` if it is not given): `slope = (P_Full - P_Epsilon)`

Then the power consumption is:
` P(load) = P_Epsilon + load * slope ` when `load > 0`, and `P_Idle` when `load = 0`.

If there is no objection to this model, a PR for the energy_plugin will be coming soon, with a script to update the platform XML files from @mpoquet.

**Comment by mquinson** [comment]
There is something I don't get here. Since we can convert automatically from the old `idle:one:all` to the new `idle:epsilon:all` syntax, why are we transitioning ? Why can't we just parse it as `idle:one:all` in the XML file and do the right thing to compute internally the `epsilon` part when parsing?

This whole story is driving me nuts since maybe one week, as I'm trying to figure a transition path for our users. That's nasty because we change the meaning of numerical values with no warning. 
I was thinking of bumping the XML version, but since that's not a backward-compatible change, we cannot bump to 4.2. We must use 5 instead, which seems overrated for that change (and mandates further cleanups in the XML file while we are at it).
Since that's a property used in a plugin, I was thinking of renaming the property to detect whether the users are still using the old syntax. I even implemented a patch requesting a property called `wattage_per_state` and proposing the right values if the user is still using `watt_per_state`. And then I am wondering whether we should force that change to our users.

@mpoquet, @mommessc, @alegrand, am I missing something that mandates the use of Epsilon value in the xml files?

**Comment by mpoquet** [comment]
Converting from the old `idle:one:all` to `idle:epsilon:all` is indeed possible for all previous cases, but the new syntax enables a wider range of properties than the old one. **Our main problem was that it was impossible to express a non-binary power consumption for single-core machines with the old syntax** – which we would like to observe on non-binary-loaded machines in ptask_L07.

**Pseudo-proof**. For any machine of `n` cores, the old code computes `epsilon` from the intersection of the `load=0` line and the line that passes through `(load=1/n, power=one)` and `(load=1, power=full)`. The two points form a degenerate line (the power*load plan) for 1-core machines, as the two points are identical since `load=1/n=1` and `power=one=full` (by definition of `one` and `full`).

As the new syntax avoids the `n=1` degenerate case of the previous model, it allows users to express this behavior while keeping the energy model code very simple, as the code simply applies the exact same linear function for all machines. I also feel like the new syntax is more transparent about what is computed than the previous one for new users, but as most users probably met the new syntax in the (pdf) tutorial with clear and explicit power consumption plots, documentation patched this problem for the old syntax.

**I however agree that breaking the platform API for this corner case may be too much. Allowing users to specify `epsilon` for 1-core machine would be fine without breaking the previous syntax.** The annoying part about this is that `epsilon` should be set for all pstates, but not in the `watt_per_state` property if we want the old `idle:one:full` syntax to be consistent and preserved. The only way I can think of to allow users to define `epsilon` is in a dedicated host property, but I feel like this is not desirable as the energy platform syntax is already quite far from simple.

**Using a different name for the new syntax would fix the API break problem with the good properties of the new syntax.** The only problem I see with it is the maintenance cost, as the old syntax requires more computations to determine `epsilon` and to pick an arbitrary values when `n=1`, as well as the deprecation management cost. But it looks like managing deprecation is quite common in SimGrid so it may be the best way to go.

As a summary, here is a table that excludes to just keep the old syntax that prevents our use case.

|      | New syntax                                                                                                | Old syntax + epsilon                       | New and old syntax cohabitation                                                          |
|------|-----------------------------------------------------------------------------------------------------------|--------------------------------------------|------------------------------------------------------------------------------------------|
| Pros |  - **Consistent and generic, handles all cases**<br/> - **Straightforward energy plugin code (yay for maintainers)** | - No API break (yay for users) |  - No API break (yay for users)<br/> - **Benefits from new syntax fully there in some versions** |
| Cons | - **Breaks platform API**                                                                                     | - **Even more complex energy platform XML syntax** | - Code kept non simple to manage the old syntax<br/> - Glue code probably needed, as well as deprecation management code |

PS: @Mommessc and I's energy model PR included a syntax change and an energy plugin code clean. I think the previous plugin could be cleaned without the syntax change, notably to
- only compute `epsilon` once per pstate (it was done at each pstate modification if I remember correctly)
- use the same simple power consumption formula in all cases (assuming a deterministic arbitrary value for `epsilon` is picked in the degenerate case `n=1`)

**Comment by mquinson** [comment]
Let's go for one year of cohabitation between the two syntaxes, then.

Does the current git version seem ready to release to you?

Thanks, Mt.

**Comment by Mommessc** [comment]
Hello,

Without counting the doc that has to be updated, I think the code is ready to release now.

**Comment by mquinson** [comment]
Hello, thanks for your feedback. I'd like in particular to have a review of my converting code that is here: https://github.com/simgrid/simgrid/blob/master/src/plugins/host_energy.cpp#L346

As for the doc, I made it so that it is now visible here: https://simgrid.frama.io/simgrid/Plugins.html#plugin-host-energy Is there anything in particular that we should update here?

Thanks again for your work and for this review.

**Comment by Mommessc** [comment]
Regarding the code:

1 We are missing the fact that **Idle:AllCores** was only accepted for the case of single core hosts. I think with this new version one could design a platform with the obsolete **watt_per_state** property on a multi-core host, which would lead to a multi-core host having the same power consumption (**AllCores**) regardless the number of active cores or the load of the cores.
Maybe we do not care since we mark this syntax as deprecated, but we have to be aware of that.

2 I would change the comment of [this line](https://github.com/simgrid/simgrid/blob/master/src/plugins/host_energy.cpp#L350) to *Case: Idle:OneCore:AllCores* since we are dealing with the old syntax.


Regarding the doc, two tables ([this one](https://github.com/simgrid/simgrid/blob/master/src/plugins/host_energy.cpp#L54) and [that one](https://github.com/simgrid/simgrid/blob/master/src/plugins/host_energy.cpp#L77)) are not included.
It may also be the case for other tables directly retrieved from the source code.

**Comment by mpoquet** [comment]
I'm proofreading the energy plugin code from last commit (b4ace96f8a).

**Everything seems fine**. I just wonder how can `cpu_load` be greater than 1 on [line 265](https://github.com/simgrid/simgrid/blob/b4ace96f8a501a6659817d9741aeb103cbcfd2c4/src/plugins/host_energy.cpp#L265)? I could not open the [coverage report for this file](https://ci.inria.fr/simgrid/job/SimGrid-DynamicAnalysis-Coverage/label=debian-testing-dynamic-analysis/1352/cobertura/src_plugins/host_energy_cpp/), but I feel like an assert could replace this line if it is there to check internal consistency.

**Comment by mquinson** [comment]
Better now ?
@Mommessc: I've reformated the doc quite a bit.
@mpoquet : I've changed the if into an assert as you advised.

Could you please pay attention to that conversion code? I'm really not trusting myself on this one...

**Comment by mquinson** [comment]
After all this time, I think that this is closed. Thanks for your precious help.
