### ISSUE TITLE
S4U bug: it seems all simulated process PIDs are 0

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#195]

**Comment by mquinson** [comment]
I'm surprised, because the following example seem to work fine.
https://github.com/simgrid/simgrid/blob/master/teshsuite/s4u/pid/pid.cpp

How are you trying to retrieve the pid?

**Comment by mquinson** [comment]
Ah, ok, I understood. The pb is in the logs using %i in the format, not in this_actor::pid()

Gime one sec.
