### ISSUE TITLE
No MSG_comm_waitany in Java

### ISSUE THREAD

**Issue by frs69wq** [simgrid/simgrid#20]
The equivalent of this function that allows developers to implement multiple "listeners" in a single process is missing in the Java binding. 

something like 
Vector<Comm> myListeners = new Vector<Comm>();
[...]
int completedOne = myListeners.waitAny() 

would be awesome!

Thx.

**Comment by mquinson** [comment]
Hello,

I just implemented this, so I'm closing the bug. But it's not tested yet, so feel free to reopen on need.
