### ISSUE TITLE
Segfault with thread contexts factory and mmap privatization occasionally

### ISSUE THREAD

**Issue by agiersch** [simgrid/simgrid#204]
The test allred from smpi-mpich3-coll-thread (with thread contexts factory and mmap privatization) occasionally segfaults on thread exit:

    teshsuite/smpi/mpich3-test/coll$ ../../../../smpi_script/bin/smpirun \
        -platform ../../../../examples/platforms/small_platform_with_routers.xml \
        -hostfile ../../hostfile_coll --cfg=smpi/running-power:1e9 \
        --cfg=smpi/async-small-thresh:65536 --cfg=contexts/factory:thread \
        --cfg=smpi/privatization:1 -np 4 ./allred
    [...]
     No Errors
    Segmentation fault.
    
Backtrace:

    #0  do_lookup_x (...) at dl-lookup.c:98
    #1  0x00007ffff7de596d in _dl_lookup_symbol_x (...) at dl-lookup.c:737
    #2  0x00007ffff6a4da75 in do_dlsym (...) at dl-libc.c:97
    #3  0x00007ffff7deaaa4 in _dl_catch_error (...) at dl-error.c:187
    #4  0x00007ffff6a4dabf in dlerror_run (...) at dl-libc.c:46
    #5  0x00007ffff6a4db78 in __GI___libc_dlsym (...) at dl-libc.c:210
    #6  0x00007ffff730dfbe in pthread_cancel_init ()
        at ../nptl/sysdeps/pthread/unwind-forcedunwind.c:55
    #7  0x00007ffff730e16c in _Unwind_ForcedUnwind (...)
        1at ../nptl/sysdeps/pthread/unwind-forcedunwind.c:129
    #8  0x00007ffff730c5d0 in __GI___pthread_unwind (...>) at unwind.c:129
    #9  0x00007ffff7307365 in __do_cancel () at pthreadP.h:280
    #10 __pthread_exit (...) at pthread_exit.c:29
    #11 0x00007ffff7c12df9 in xbt_os_thread_exit (...)
        at [...]/src/xbt/xbt_os_thread.c:251
    #12 0x00007ffff7c938ab in stop (...)
        at [...]/src/kernel/context/ContextThread.cpp:205
    #13 simgrid::kernel::context::ThreadContext::wrapper(void*) (...)
        at [...]/src/kernel/context/ContextThread.cpp:159
    #14 0x00007ffff7c16131 in wrapper_start_routine (...)
        at [...]/src/xbt/xbt_os_thread.c:154
    #15 0x00007ffff7306064 in start_thread (...) at pthread_create.c:309
    #16 0x00007ffff6a1862d in clone ()
        at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
    
Even if I don't fully understand what's going on, I suspect that a segment switch is occurring while the thread is running some cleanup handlers.

A fix was tempted in commit c7829c256a041aae9a60454263de30188b3f2fcc, but it miserably failed for two (unrelated) reasons.
First, when MC is enabled, all tests with thread contexts factory seem to deadlock (see [build \#2417 on Travis CI](https://travis-ci.org/simgrid/simgrid/builds/255582989)).
Secondly, `pthread_cleanup_pop()` fails to compile with MinGW (see [build \#2369 on AppVeyor](https://ci.appveyor.com/project/mquinson/simgrid/build/2369)).

**Comment by mquinson** [comment]
Is the problem related to this test (allread) or to the privatization+factory? 

Are you still confident that your proposed fix should be improved to overcome these two issues, or do you now think that it won't work? In the first case, could you please open a pull request with this commit so that we get a chance to improve the patch?

Thanks, and welcome back.
Mt

**Comment by agiersch** [comment]
IMO, the problem is related to privatization and thread factory.

I don't understand why I can only observe the problem with the allred example.  I didn't find any occurence on the CI servers either.

Since the patch doesn't work properly, I suggest to keep this bug report open for the record, and to wait and see if:
* somebody else observes the problem, or
* we can better understand what's going on, and imagine a better solution, or
* the problem disappears by itself, for example with a system update.

Arnaud

**Comment by agiersch** [comment]
Some more informations : 
The problem occurs when using gcc and gold linker.
I can't reproduce it with clang, or if I remove /usr/lib/gold-ld from my PATH.

**Comment by mquinson** [comment]
Additional info: this does not seem to be connected to LTO as it fails (according to Arnaud's tests) with gold linker and without LTO.

**Comment by mquinson** [comment]
I'm not sure that it's interesting to investiguate this bug. It probably lays in gold-ld, which is ways beyond my concerns...
