### ISSUE TITLE
Recreate CI virtual machines.

### ISSUE THREAD

**Issue by adegomme** [simgrid/simgrid#210]
Due to a manipulation mistake from the CI team, all of our VMs used fo jenkins builds are gone.

This means we will have to start over and recreate new images. We can recreate the ones we had before or try new things. If you have ideas of new systems/configurations/compilers we should use, feel free to submit that here.

The ones we had : 

| OS version | Compiler name and version |
| --- | --- |
| CentOS Linux 7.2.1511 64 bits | GNU 4.8.5 |
| Debian Testing 32 bits | GNU 6.3.0 |
| Fedora Rawhide 64 bits | GNU 7.1.1 |
| FreeBSD 11.0-RELEASE-p1 64 bits | Clang 5.0-dev |
| NetBSD 7.99.35 64 bits | GNU 7.1.0 |
| Nixos 17.03 64 bits | GNU 6.3.0 |
| OpenSuse 42.1 64 bits | Clang 3.7.0 |
| OSX Mavericks 10.9.5 64 bits | AppleClang 6.0.0.6000051 |
| Ubuntu 14.04 32 bits | GNU 4.8.4 |
| Ubuntu 14.04 64 bits | GNU 4.8.4 |
| Windows 7 64 Bits - MinGW64 with MSYS | GNU 5.3.0 |
| Debian Testing 64 bits | GNU 6.3.0 |

Another thing is we should try to unify the way these are built, and save this in a corner somewhere in order to avoid such case in the future.
We could consider using something like puppet to keep recipes versionned, but I'm not sure it can be used with CI's cloudstack . If someone in the project has some experience with this, please contribute.

This is also valid for jenkins configuration, as it would be rather annoying to lose it, and we didn't git it yet. Do we have a private repository we could use to store this potentially critical data ? I installed the plugin to do this with jenkins a while ago, but did not set it up yet.

**Comment by randomstuff** [comment]
Debian stable?

**Comment by adegomme** [comment]
After some non conclusive attempts with ansible, it was quicker to put them back together by hand from the templates made available ater the crash by other groups on ci.

For reference, from the templates, what we need to add is 
```shell
#debian/ubuntu
apt-get install gcc g++ gfortran automake cmake libboost-dev openjdk-8-jdk openjdk-8-jre libxslt-dev libxml2-dev libevent-dev libunwind-dev libdw-dev htop git python3 xsltproc libboost-context-dev
#for dynamicanalysis: 
apt-get install jacoco libjacoco-java libns3-dev pcregrep gcovr ant lua5.3-dev sloccount

#fedora
dnf install libboost-devel openjdk-8-jdk openjdk-8-jre libxslt-devel libxml2-devel xsltproc git python3 libdw-devel libevent-devel libunwind-devel htop lua5.3-devel

#netbsd
pkg_add cmake gcc7 boost boost-headers automake openjdk8 libxslt libxml2 libunwind git htop python36

#opensuse
zypper install cmake automake clang boost-devel java-1_8_0-openjdk-devel libxslt-devel libxml2-devel xsltproc git python3 libdw-devel libevent-devel libunwind-devel htop binutils ggc7-fortran

#freebsd
pkg install boost-libs cmake openjdk8 automake libxslt libxml2 libunwind git htop python3  automake gcc6 flang elfutils libevent
#+ clang-devel from ports

#osx
brew install cmake boost libunwind-headers libxslt git python3 

```
