### ISSUE TITLE
S4U: Actor::kill() doesn't really kill and segfaults

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#222]
There seems to be problems with kill().  Here is a MWE that shows both LLM warnings, and weird 'not dead' behavior followed by a segfault...
[mwe_kill_actor_does_not_kill.zip](https://github.com/simgrid/simgrid/files/1275599/mwe_kill_actor_does_not_kill.zip)

**Comment by mquinson** [comment]
Hello @henricasanova, 

could you please test again whether this problem was solved by the recent changes made by @agiersch ?

Thanks, Mt

**Comment by henricasanova** [comment]
So, Arnaud's changes fix me MWE, which is great since that indicates some progress. Now, in my real app, I still have problems. Essentially, the behavior is as follows:
  - I have an actor create another actor, which then creates n actors
  - For each of these actors have a  onExit() call that causes it to print "bye!" when it dies
  - I kill these n actors, and I get n "bye!" messages
  - But when the simulation ends, I get the usual "actors are still alive"  ("Deadlock...") message, and 2 of the actors who printed "bye" are not actually dead  (the other n-2 are!)

**Bottom-line: The onExit()-passed function was called  but an actor still lingers**


Let me continue investigating and see if I can can come up with a MWE. Coming up with MWE is getting very labor intensive now :)

**Comment by henricasanova** [comment]
After investigating, I am going to close this issue, because Arnaud's fix fixed it. But there is in fact another issue, that I'll open shortly.  Making progress!
