### ISSUE TITLE
MSG_task_get_flops_amount() is not documented

### ISSUE THREAD

**Issue by mickours** [simgrid/simgrid#223]
Hi,

I am currently implementing job preemption in Batsim (that is based on Simgrid). To reflect the preemption cost properly I'd like to have access to the remaining (or already computed) amount of work of an MSG ptasks before killing it.

I found a ``getRemains()`` function used in ``surf/ptask_L07.cpp`` that seems to correspond to what I need but it is not accessible in MSG. Is it possible to expose this in the MSG API?

**Comment by mickours** [comment]
I finally find a way to get what I need from MSG using ``MSG_task_get_flops_amount(task);`` that returns exactly what what I was looking for when the task is started: the remaining amount of work between 0 and 1 for a parallel task.
I did not find it at first, because It not documented.

**Comment by mquinson** [comment]
This function should actually be documented...

**Comment by mickours** [comment]
The problem is that this function actually returns the flops amount (but not the parallel flops amount) before the task start, but when the task has started it return the remaining amount of work of the task (for parallel also).

So we should change the behavior of this function to return only the flops amount and create another function that return the remaining works directly. But it is not *only* documentation and it breaks the existing API.

**Comment by mquinson** [comment]
If I understand correctly, you propose to:
 - [  ] change  `MSG_task_get_flops_amount()` so that it always return the initial amount 
 - [  ] add a `MSG_task_get_flops_remaining()` with the current behavior of  `MSG_task_get_flops_amount()`

What's not clear to me is whether there is something to do for the parallel tasks specifically.

**Comment by frs69wq** [comment]
The problem with parallel tasks is that it's up to the user to define 
how the original amount given on task creation is converted into the 
combo "array of flops + matrix of bytes". For instance in SimDag, it's 
possible to use Amdahl's Law for that, but it can be anything. Then, I 
don't see how SimGrid could return something meaningful for the 
evolution of parallel tasks.


Le 01/10/2017 à 01:38, Martin Quinson a écrit :

**Comment by mickours** [comment]
Has I said, after the task begins, It do not return the amount of flops at all: It returns the remaining amount of work which is a value between 0 and 1. This value comes directly from the underlying model and works for either parallel or sequential tasks and for communication and computation (even it comes from the compute object: this is the only used for parallel task).

I put the code here for convenience:
https://github.com/simgrid/simgrid/blob/934e15f8ffc473c09214dd3dcbd4a926d2fa0846/src/msg/msg_task.cpp#L231-L237
 
So I agree with the first point but the second function should be named something like ``MSG_remaining_work_ratio()`` and return the [0,1] value that represent the task progress.

**Comment by mquinson** [comment]
A pull request introducing such a function would be more than welcome. Even more if a call to that function is added to the tests (either in an existing example, or in another meaningful example).
Thanks in advance ;)

**Comment by mickours** [comment]
After discussion, It is not working properly for sequential tasks.

The idea is to keep old implementation for sequential task and do not allow the parallel task to be call with it. Also we keep the new ``MSG_remaining_work_ratio()`` but we need to change the output for sequential task to give a ratio and not an amount of flops.
