### ISSUE TITLE
s4u::Actor::kill() doesn not really kill when victims are doing a join() ??

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#225]
This yet another "kill() doesn't really work" issue, for which I am attaching yet another Minimum Working Example (just type make run and it should work...).  Here is the setup:

- A grandparent actor creates a child actor
- The child creates a grandchild actor
- The grandchild computes for a long time
- The child does a join with the grandchild
- After 100 seconds, the grandparent wants to kill them both

I have two versions:
- Version #1: the grandparent does child->kill() followed by grandchild->kill()
- Version #2: the grandparent does grandchild->kill() followed by child->kill()

In both versions, the child doesn't die (the grandchild does).

PS: In my real app, the behavior is weirder even because the onExit() function call happens for both the child and the grandchild, even though one still lingers. In this MWE I haven't been able to achieve this weirdness. But regardless, the fact that actors survive a kill() isn't good.

[mwe_kill_during_join_does_not_kill.zip](https://github.com/simgrid/simgrid/files/1345304/mwe_kill_during_join_does_not_kill.zip)

**Comment by henricasanova** [comment]
Weirdly enough, it seems that Arnaud's work fixes my MWE above (which has been updated since I originally uploaded the wrong file) on Linux, but I still get the same erroneous behavior on Mac OSX.  The behavior is that the Child (who was doing a join) does not die when killed.

**Comment by agiersch** [comment]
Strange. I can't reproduce the bad behavior on Jenkins' OSX node (OSX Mavericks 10.9.5 64 bits, AppleClang 6.0.0.6000051, Boost 1.65.0). Can you post the ouput with option "--log=simix.thres:debug"?

**Comment by henricasanova** [comment]
turns out it's an issue with my machine's include directories (I tried on another machine, and it works). So we're all good.  I am closing this issue.
