### ISSUE TITLE
S4U:  segfaults when exit() without run()

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#230]
Just noticed that if one creates actor, and then simply exits (as in "exit(0)") without firs calling run() on the S4U simulation engine, then one gets a mysterious segfault.   The reason why one might care more than one might think is the following, for instance: We are developing a simulation framework on top of S4U, and users will write code with that framework, which completely hides S4U.  The framework requires some rules like: "if there is an actor of type A then there as to also be an actor of type B". So, the user creates all its actors, calls our framework, which first checks whether we have the desired mix of actors. If not, then we simply want to throw an exception, in which case the user can exit the program.  Right now, this segfault. 

Here is a stupid MWE just in case. 
[mwe_exit_before_run.zip](https://github.com/simgrid/simgrid/files/1370705/mwe_exit_before_run.zip)

**Comment by mquinson** [comment]
Hello @henricasanova, is the fix proposed by @agiersch sufficient to you? Can you live with a big fat warning in this case, or should we do more? We may decide to leak large amounts of memory in this very specific case, if it's easier.

**Comment by henricasanova** [comment]
We can leave with this as I can do a simple redesign of WRENCH that will make this warning workable.  We can leave fixing this one for got for a future SimGrid release.
