### ISSUE TITLE
Network energy models should be documented

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#235]
There is only one plugin and one example file to copy over from https://github.com/betsegawlemma/simgrid

Note that this code is also using Ecofen (a modified NS3 version to have an energy model), and that this part must probably be protected with `#ifdef`s

**Comment by mquinson** [comment]
The code was integrated, but I'm keeping the bug open as a reminder to document it.

**Comment by TruongThaoNguyen** [comment]
Hi
I would like to evaluate the link energy. Do you mean the bug is in file suft_interface.cpp?  Some code like this should be add to surf_plugin_description[]  (line 52) 
`{"Link_Energy", "Link energy consumption.", &sg_link_energy_plugin_init}, `
I use the Simgrid version 3.19.1

**Comment by mquinson** [comment]
Good idea. I just did it in the git version.

But the bug is more about the documentation, that should explain how to use this plugin.

**Comment by Shurakai** [comment]
Just thought I'd point out that there is limited documentation here: http://simgrid.gforge.inria.fr/simgrid/3.20.90/doc/group__SURF__plugin__energy.html

**Comment by mquinson** [comment]
You are right, @Shurakai this is actually documented. Thus closing.

Thanks,
