### ISSUE TITLE
Memory problems after MSG_process_kill (bad refcounting?)

### ISSUE THREAD

**Issue by mpoquet** [simgrid/simgrid#243]
# Problem description
I develop the Batsim simulator and I observed that it breaks with recent SimGrid versions when jobs are *killed*, that is to say when *MSG_process_kill* is used in a certain way.

The bug has been introduced in commit d68a0ac239 (2017-06-06) and still exists with up-to-date SimGrid (tested with 03c1a9b98 (2017-11-21)).  
The commits before it work (including the one just before: 863aeead8).

Commit d68a0ac239 is about (smart) pointer management.
It may have introduced too aggressive memory deallocations and invalid memory management as invalid memory operations are done in my case after this commit.

Valgrind outputs (the initial Thread 2 error is not related to SimGrid):
- when it works (old, 863aeead8): [good_863aeead8.vgout](https://gist.github.com/mpoquet/906d2015971ed6b802245ddc71a83dbc#file-good_863aeead8-vgout)
- when it stops on an assert (old+1, d68a0ac239): [bad_d68a0ac23.vgout](https://gist.github.com/mpoquet/906d2015971ed6b802245ddc71a83dbc#file-bad_d68a0ac23-vgout)
- when it crashes silently (current, 03c1a9b98): [bad_03c1a9b98.vgout](https://gist.github.com/mpoquet/906d2015971ed6b802245ddc71a83dbc#file-bad_03c1a9b98-vgout)

# How to reproduce?
I tried to produce a MWE in vain, as the problem does not appear with simpler examples :(.

I propose the following scripts to:
- download, compile and run Batsim (simulator)
- download, compile and run Batsched (scheduler)

How to install dependencies is written (programmatically) [there](https://github.com/oar-team/batsim/blob/master/environments/steps/batsim_dependencies.yaml).

## Batsim
```bash
# Get Batsim
curl https://gitlab.inria.fr/batsim/batsim/repository/issue37_broken_kills_with_recent_sg/archive.tar.bz2 > batsim.tar.bz2
tar -xf batsim.tar.bz2
mv batsim-issue37_broken_kills_with_recent_sg* batsim
BATSIM_DIR=$(realpath batsim)

# Build Batsim (may require many dependencies...)
mkdir -p ${BATSIM_DIR}/build
cd ${BATSIM_DIR}/build
cmake ..
make

# Prepare launch output dir
mkdir -p ${BATSIM_DIR}/expe_out

# Launch Batsim
${BATSIM_DIR}/build/batsim \
    -p ${BATSIM_DIR}/platforms/cluster512.xml \
    -w ${BATSIM_DIR}/workload_profiles/issue32.json \
    -e ${BATSIM_DIR}/expe_out/out \
    --mmax-workload -vdebug -m master_host0

# Batsim should now wait for the scheduler (batsched) to connect
```

## Batsched

```bash
# Get Batsched
curl https://gitlab.inria.fr/batsim/batsched/repository/master/archive.tar.bz2 > batsched.tar.bz2
tar -xf batsched.tar.bz2
mv batsched-master* batsched
BATSCHED_DIR=$(realpath batsched)

# Build Batsched
mkdir -p ${BATSCHED_DIR}/build
cd ${BATSCHED_DIR}/build
cmake ..
make

# Launch Batsched
${BATSCHED_DIR}/build/batsched -v killer2
```

**Comment by mquinson** [comment]
I fear that this is the same problem that with #243: the process get freed as soon as it teminates and you should not access it afterward. This is the semantic of the MSG API, dictated by the fact that C has no automatic refcounting. 

If you don't want to convert BatSim to S4U (despite what you should), you can try to manually increase/decrease the refcount of each processes when you take references on them. That should work, but I'd not go that way myself.

**Comment by mquinson** [comment]
With more thinking, I'd say that this bug is definitely in your code. If you hold a reference on a process that may die (or get killed), then you want to use MSG_process_ref() to make sure that it's not freed before you release your reference.

Do you agree? Can we close the bug report?

**Comment by mpoquet** [comment]
Yes I agree.
In fact I only realized that MSG_process_ref/unref had been introduced while submitting [issue 248](https://github.com/simgrid/simgrid/issues/248) :(.

I'll reopen the issue if this fix is not enough.
