### ISSUE TITLE
Two broken links on SimGrid website

### ISSUE THREAD

**Issue by stanisic** [simgrid/simgrid#251]
On the http://simgrid.gforge.inria.fr/Publications.php, links for the first two publications are broken:

 1. Franz C. Heinrich, Tom Cornebize, Augustin Degomme, Arnaud Legrand, Alexandra Carpen-Amarie, Sascha Hunold, Anne-Cécile Orgerie, Martin Quinson. Predicting the Energy Consumption of MPI Applications at Scale Using a Single Node. In Proc. of the 19th IEEE Cluster Conference, 2017.
      + **PDF link is not good**
  2. Degomme, Augustin, Legrand, Arnaud, Markomanolis, Georges, Quinson, Martin, Stillwell, Mark S, Suter, Frédéric. Simulating MPI applications: the SMPI approach. IEEE Transactions on Parallel and Distributed Systems, 2017. (8)
      + **10.1109/TPDS.2017.2669305 link is not good**

**Comment by alegrand** [comment]
Thanks. I fixed it in commit e2a97eaf65162f647f5cf27175791bb570506b0a.
