### ISSUE TITLE
Fix (ab)use of CMake `install`

### ISSUE THREAD

**Issue by Flamefire** [simgrid/simgrid#257]
In the file https://github.com/simgrid/simgrid/blob/aec830b8423c13c5c31e3db71361a449bfacd8ed/tools/cmake/Distrib.cmake all `install` calls are with `DESTINATION $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/<something>` this is (at least) overly verbose.

- `DESTDIR` is handled by `make install`. I even guess you would get double-paths if you try `export DESTDIR=Foo; cmake . && make install` which makes this a bug
- All DESTINATIONs are already relative to `CMAKE_INSTALL_PREFIX`

I therefore suggest removing all `$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/` and check for further (ab)uses of `DESTDIR` and `CMAKE_INSTALL_PREFIX`

**Comment by mquinson** [comment]
Yeah, this is a misinterpretation of how we build Debian packages. Fixed now.
