### ISSUE TITLE
Segfaults when killing an MSG process before it was started

### ISSUE THREAD

**Issue by mickours** [simgrid/simgrid#260]
Using the last Simgird version (093347cf872dbd) killing an MSG process just after it was started lead to a segfault. The killing process finishes normally but it seems that the process is still in the main loop and it segfault when Simgrid try to run it.

The first segfault is in ``/src/kernel/activity/ExecImpl.cpp`` in the post function ``simgrid::kernel::activity::ExecImpl::post()``  on line 75. I try to patch this because it seems that a simple test  on the surfAction existence was missing. Here is the patch:
```diff
diff --git a/src/kernel/activity/ExecImpl.cpp b/src/kernel/activity/ExecImpl.cpp
index 521785dcc..a6d1ff8c9 100644
--- a/src/kernel/activity/ExecImpl.cpp
+++ b/src/kernel/activity/ExecImpl.cpp
@@ -75,7 +75,7 @@ void simgrid::kernel::activity::ExecImpl::post()
                                  /* If the host running the synchro failed, notice it. This way, the asking
                                   * process can be killed if it runs on that host itself */
     state = SIMIX_FAILED;
-  } else if (surfAction_->get_state() == simgrid::kernel::resource::Action::State::failed) {
+  } else if (surfAction_ and surfAction_->get_state() == simgrid::kernel::resource::Action::State::failed) {
     /* If the host running the synchro didn't fail, then the synchro was canceled */
     state = SIMIX_CANCELED;
   } else if (timeoutDetector && timeoutDetector->get_state() == simgrid::kernel::resource::Action::State::done) {
```
This patch fix the first segfault but another one appears in the ``void SerialRawContext::run_all()`` function at the line 310: https://github.com/simgrid/simgrid/blob/c139b4e36702f58bd8a75e87cf537959da82dbc9/src/kernel/context/ContextRaw.cpp#L304-L311

It seems that the process is still in the ``simix_global->process_to_run`` but process context failed to be resumed.

I think this should be avoided by adding a test in the ``SIMIX_process_kill`` function: It already ignore kill for finish processes maybe it should ignore it also for not started ones?

https://github.com/simgrid/simgrid/blob/c139b4e36702f58bd8a75e87cf537959da82dbc9/src/simix/ActorImpl.cpp#L461-L466

Or perhaps, it should not be added to the  ``process_to_run`` list if it has not started.

https://github.com/simgrid/simgrid/blob/c139b4e36702f58bd8a75e87cf537959da82dbc9/src/simix/ActorImpl.cpp#L517-L523

**Comment by mquinson** [comment]
Hello,

I just augmented the S4U test to investiguate this bug, and it seems to not happen in S4U. I thus think that this is a refcounting issue. What happens if you do something like:
```
process = MSG_process_create(...)
MSG_process_ref(process);  <---
MSG_process_kill(process);  
//MSG_process_unref(process);  <--- not doing this leads to a memleak. Doing this may lead to the segfault
```

The good thing of C++ is that the refcounting code is automatically generated by the compiler.

**Comment by mickours** [comment]
With ``MSG_process_ref(process);`` I got a new segfault and an empty stack that point to `0x0`:
```
Thread 1 "batsim" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
```
Not better...

Looks like S4u is the way to go.

**Comment by mquinson** [comment]
Before you convert everything right away, you may want to provide a MWE so that we get a chance to debug it. But of course, if you prefer to switch to s4u, that's even easier for me.

**Comment by mquinson** [comment]
I failed to reproduce this bug, and you did not provide any MWE. Do you think you'll be able to bring more information, or would you agree to close this bug, maybe?

Thanks for your feedback,

**Comment by mpoquet** [comment]
Batsim has switched to S4U in the meantime, but the problem still exists: Killing actors may result in invalid memory accesses (read/write), which sometimes causes a segmentation fault.

I failed to determine a clear condition that makes invalid reads/writes happen. This is deterministic and is more likely to happen when the kill occurs just after the start, but it may also happen at any time. As we could not produce a MWE, I'm fine with closing this issue (for now).

**Comment by mquinson** [comment]
Ok, let's close it for now, then. Thanks.
