### ISSUE TITLE
SMPI : tracing of MPI_Wait/all/any broken

### ISSUE THREAD

**Issue by adegomme** [simgrid/simgrid#269]
In january there was a rewriting of this part. It seems that the endlink event generation after a successful wait has been removed. 
Before https://github.com/simgrid/simgrid/commit/bfcfbe21c80a625d2a59e9b0b215e52d061dfe84  and its friends, we were using a local structure to save information about the request. Indeed this request is "lost" at the end of smpi::Request::wait/any/all as the handle for a successfully finished request is set to MPI_REQUEST_NULL (following the standard). 

The new version just ignores this case, thus not generating any end link event in the trace.

We should 
1/ fix the issue: either by putting back the local structure as it was, or finding a better solution (I don't think we can set the MPI_REQUEST_NULL only in smpi_pmpi_request instead of in finish_wait and such, as it is used internally elsewhere).
2/ add tests for this case.

MWE : just trace the exemples/smpi/trace and check that there are line starting by 15 (startLink), but no line starting by 16 (endLink) ... Btw, why don't we check the output of this test in the teshfile ?

**Comment by agiersch** [comment]
Closed by mistake, sorry.

**Comment by adegomme** [comment]
It was indeed closed, and tests were added painfully, to check that the output trace stays stable.
