### ISSUE TITLE
Use std::function for callbacks

### ISSUE THREAD

**Issue by Shurakai** [simgrid/simgrid#275]
There are many places where callbacks are currently restricted to simple functions. Using std::function would allow us to provide more flexibility with backwards compatibility.

See for instance the typedefs in function_types.h for an idea of where to look. The C users can continue to use those typedefs but the usage in the SG codebase should be converted; for instance,

`xbt_main_func_t` becomes `std::function<int(int, char*)>`

**Comment by randomstuff** [comment]
I did quite a lot of those already.

For example, `xbt_main_func_t` is AFAIR supposed to be limited to the C API. The underlying API is actually :

```
static ActorPtr create(const char* name, s4u::Host* host, std::function<void()> code);
```

I'd say most of the callback types in `function_types.h` are compatibilty things and there's usually already a C++ based API which accepts arbitrary functors.

**Comment by Shurakai** [comment]
SMPI & SIMIX use `xbt_main_func_t`  and that needs to be removed as well.

**Comment by mquinson** [comment]
@Shurakai do you plan to do this yourself, maybe? If not, I'm considering closing the issue to keep the issue tracker slim and usable. There is so much such refactoring that we should do and could bloat the issue tracker if reported this way...

**Comment by Shurakai** [comment]
@mquinson I am in fact working on this whenever I get the chance, but there's only so much I can do since I'm working primarily on my research.

You can label this issue "improvement", if you want.

**Comment by mquinson** [comment]
Please do not break the C API while doing this. Some people rely on it..

**Comment by mquinson** [comment]
Hello @Shurakai , do you have a list of callbacks that still need to be converted? I tend to think that we are done here (unless proven wrong of course ;)

Thanks,

**Comment by mquinson** [comment]
Ok, I do think that this is fixed. If not, please feel free to reopen.
