### ISSUE TITLE
Move const char* to std::string where possible

### ISSUE THREAD

**Issue by Shurakai** [simgrid/simgrid#276]
For instance, `template XBT_PUBLIC std::string const& get_value<std::string>(const char* name)`
requires explicitly a `const char*`. Using `std::string name = simgrid::config::get_value<std::string>("smpi/" + coll);` failed for me because it wasn't possible to convert this to `const char*`, meaning that I explicitly have to use `.c_str()` although this function even returns a string.

There are plenty of examples for `const char*` usage and I think removing them will help greatly with the cleanup.

**Comment by mquinson** [comment]
Hello,

this is not an issue, but a todo for ourselves. Using the issue tracker for such refactoring will make it very difficult to find the real issues in there, so please don't.
README.coding is the place where you want to write those, I guess.

Plus, the problem you report is not [SMART](https://en.wikipedia.org/wiki/SMART_criteria), so you'll never know whether it'd done, and it won't ever get closed. Please be more specific in your issue reports about what exactly is the problem and what you expect to be done before the issue can be closed.

**Comment by mquinson** [comment]
The whole s4u API is stringified, so I'm voting to close this issue, or to find a better, more SMART goal.

**Comment by Shurakai** [comment]
Thank you Martin, this makes the code much cleaner.
