### ISSUE TITLE
Daemonized  actor no longer daemonized after an auto-restart

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#281]
It seems that a daemonized actor is no longer daemonized once it is restarted after a host failure. I am attaching a pretty explicit MWE that showcases that behavior. 

Note that a fix is to have the actor daemonize itself by calling simgrid::s4u::Actor::self()->daemonize() each time it starts, but that's not always convenient.  Besides, the user would never expect an actor to "forget" it's daemonized I would think.

[mwe_no_longer_daemonize_after_restart.zip](https://github.com/simgrid/simgrid/files/2151546/mwe_no_longer_daemonize_after_restart.zip)

**Comment by frs69wq** [comment]
Closed by 44308b1
