### ISSUE TITLE
MPI_Init(NULL,NULL)

### ISSUE THREAD

**Issue by adegomme** [simgrid/simgrid#288]
We have an assert that should crash the code telling the user to use argc/argv instead of NULL/NULL, as we need them (smpi_actor.cpp around l260).
This seems to not be working anymore since processes became actors. Initialization keeps going on, but silently missing pieces, and then crashes happen elsewehere in the simulation (usually because MPI_COMM_WORLD is not initialized properly).

reproduce : replace MPI_Init (&argc, &argv) in any code by MPI_Init(NULL, NULL). Watch it burn.

I'm not sure what is the best solution here, as I don't really know what changed. We used to have an assert on the output of smpi_process(), which was meant to separate cleanly the illegitimate (C) use of NULL,NULL form the legitimate (in fortran). So replacing this by an "else xbt_die" would mean keeping track of the fortranness elsewhere.

We might also find a good way to just support MPi_Init(NULL,NULL), as it's legal MPI by the standard. But that would mean finding another way to give our hidden messages argc and argv to the actor init.

**Comment by adegomme** [comment]
This should be addressed by commit 2818cfc3 . 
I moved the code handling the substitutions in argc/argv to  the wrappers we now have around main. This makes MPI_Init(NULL, NULL) work now, and a test validates this. 
It was breaking MC+SMPI on my system, but it works on ci, I'll have to check what was wrong there and close this issue then.

**Comment by mquinson** [comment]
It seem that this bug can be closed now, don't you think, @adegomme ?

**Comment by adegomme** [comment]
Indeed. I was waiting for the commit to land on github, but then I forgot.
