### ISSUE TITLE
Callback weirdness when reacting to actor destructions

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#289]
It seems that callbacks are not handled correctly when trying to react to actor destruction. Here is a MWE in which some actor (Actor A) does not get a callback when another actor (Actor B) is destroyed, even though it should. Furthermore, other "actors" (the maestro and Actor B itself) get those callback...

[mwe_on_actor_destruction.zip](https://github.com/simgrid/simgrid/files/2229411/mwe_on_actor_destruction.zip)

**Comment by mquinson** [comment]
I did not check in details yet, but it seems to be a misunderstanding here: there is nothing about the actors in the logic of callbacks. Actually, I think that the callback of actor destruction is launched either in the context of maestro or the one of the dying actor... If you want it to be dispatched to all actors, then you have to loop over the actors by yourself...

I'm not sure of how we could solve this cleanly. Any idea is welcome.

**Comment by henricasanova** [comment]
yes, it has to be by on_exit, or some other mechanism by which an actor can react to another actor's death...  we can close this issue.
