### ISSUE TITLE
[s4u] semaphores do not seem available yet

### ISSUE THREAD

**Issue by mpoquet** [simgrid/simgrid#291]
Hello,

I would like the `smpi-replay-multiple` tests (and Batsim) to only use the s4u API,
but MSG seems to be required for:
- semaphores
- creating SMPI-compatible processes.

Can SMPI work without MSG processes now?
I could not find semaphores in s4u ; is the SIMIX variant meant to be used by users directly?

Best,

**Comment by mquinson** [comment]
I have a draft of s4u::Semaphore on my disk, and will try to finish and commit that soon.

What do you mean with the SMPI-compatible processes? I think Christian is using s4u actors in SMPI simulations already.

**Comment by mpoquet** [comment]
s4u semaphores have been merged in #303, thus closing this issue.

Opened #304 about fully allowing SMPI replays without MSG.
