### ISSUE TITLE
Starting a Host as OFF is not supported

### ISSUE THREAD

**Issue by gbaudic** [simgrid/simgrid#295]
Hello,

I am currently using SimGrid for experiments. In my experiments, the hosts need to be initially powered off. 

Based on the documentation, I then tried to write in my platform description file:

```
...
<host id="Host1_1" speed="100.0Mf,50.0Mf,20.0Mf,1f,1f" pstate="0" core="4" state="OFF">
    <prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0, 100.0:100.0:100.0, 152.0:152.0:152.0" />
    <prop id="watt_off" value="10" />
</host>
...
```

However, this does not work: I get the following error when using the _state_ attribute:

```
Invalid XML (XML input line 22, state 61): Bad attribute `state' in `host' element start tag.
[0.000000] /tmp/SimGrid-3.19/src/surf/xml/surfxml_sax_cb.cpp:49: [surf_parse/ERROR] Parse error at /path/to/my/platform.xml:22: Parse error in /path/to/my/platform.xml
```
(where line 22 is the one where the description of Host1\_1 starts)

Looking at the C++ code referenced by this error, this _state_ attribute seems to be unsupported, despite the documentation saying it exists (but is optional). 

What am I missing here?

Regards,
Gwilherm Baudic

**Comment by alegrand** [comment]
In the section "New in DTD version 4 (in SimGrid 3.13):" of simgrid-git/src/surf/xml/simgrid.dtd, I read:
   - In <host> and <link>, attributes availability and state are gone.
     It was redundent with state and availability traces, and with peak values.
So it seems like the DTD was simplified at this point and state can only be set through the state_file attribute.
