### ISSUE TITLE
Is SMPI and parallel task (ptask) can run together? Does it even make sense?

### ISSUE THREAD

**Issue by mickours** [simgrid/simgrid#298]
Using Batsim, I would like to mix SMPI application (HPC jobs model) and Ptask based application (Big Data jobs model) in the same simulation.

The question is: does it make sense? Keep in mind that we want a coarse grain simulation for resource and job management system, so we don't mind if there is some imprecision in the model. 
I tried to get some information about that on the doc but it is still TBD: http://simgrid.gforge.inria.fr/simgrid/3.20.90/doc/models.html

FYI, even if it has no sense, I just tried it with Batsim (because it is pretty simple to setup :)), and it seems to work (until a certain point where it deadlock but it might be related to my code).

**Comment by mquinson** [comment]
Hello,

yes it kinda makes sense. Your simulation should remain sound if you mix HPC jobs represented with SMPI application and parallel executions with the LV08 model. It should :)

I'd be really surprised if the deadlock comes from this mixture.

And finally, please use the mailing list for such question, not the issue tracker ;)

Thanks,
