### ISSUE TITLE
[smpi] manually deployed replay is not s4u-friendly

### ISSUE THREAD

**Issue by mpoquet** [simgrid/simgrid#304]
Continuing #291 here.

I tried to remove the MSG calls from the `smpi/replay_multiple_manual_deploy` example but `SMPI_app_instance_register` only supports `xbt_main_func_t`, not `std::function`-like.

I can hack a function that supports `std::function`, but I'm not sure this is desired as the SMPI public interface seems to be in C at the moment.

**Comment by mquinson** [comment]
Well, if you want to be s4u-friendly, being usable from C++ seems to be a must. The msg.h file is full of `#ifdef cplusplus` right in the middle to help C++ calling code.

**Comment by mpoquet** [comment]
I actually could get rid of MSG in the `smpi/replay_multiple_manual_deploy` example (25405df82) without any modification to SimGrid.

Giving `nullptr` to `SMPI_app_instance_register` is fine when the function is not to be deployed internally by SimGrid. I documented this possibility into `SMPI_app_instance_register`'s doxygen description in 8e44d1dea.
