### ISSUE TITLE
[MC] please provide an option to make MPI_Send asynchronous

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#31]
When there is enough underlying buffering, this operation becomes asynchronous and non-blocking. It would thus be useful in practice to study the application behavior when this hypothesis holds, before moving to the harder case where it does not hold.

Thanks,

**Comment by degomme** [comment]
We have two options already in SMPI to specify this behavior, but I think they are ignored by the MC (or don't work with it). The first (smpi/send_is_detached_thresh) is the size at which the MPI_Send will switch between internally buffered (and then release of the sender) and normal mode (wait until completion, and no internal buffer used). The second (smpi/async_small_thres) describes the size before which the MPI_Send (and Isend) is performed immediatly, without waiting for the corresponding MPI_Recv to be posted. If needed I can elaborate more, but you can find some details on http://simgrid.gforge.inria.fr/simgrid/3.12/doc/options.html . But with MC I think this is disabled or at least untested, as MArtin said.

**Comment by Shurakai** [comment]
FYI I renamed the smpi/async_small_thres to smpi/async_small_thresh in 9cf73cc09740865d0de90546a12b2e2d74cfaf6f

**Comment by mquinson** [comment]
This was implemented this summer. You can now specify `--cfg=smpi/buffering:infty` to require infinity-buffering mode or `--cfg=smpi/buffering:zero` to go for 0-buffering mode.
Thus closing.
