### ISSUE TITLE
Passing arguments to application in simgrid3.19

### ISSUE THREAD

**Issue by TruongThaoNguyen** [simgrid/simgrid#310]
Hi,
I would like to simulate the my custom caffe_mpi using Simgrid3.19. 
My command like this 
`./SimGrid-3.19/build/bin/smpirun -np 10 -hostfile ./SimGrid-3.19/examples/smpi/nguyen-simple-example/hostfile -platform ./SimGrid-3.19/examples/platforms/energy_platform.xml --cfg=smpi/display-timing:1 --cfg=smpi/host-speed:1000000 path/to/caffe_mpi/build/tools/caffe train --solver=path/to/cifar10-test/solver.prototxt`

I want to pass `train --solver=./cifar10-test/solver.prototxt` to caffe but it did not work and show some notification that caffe do not recognize any argument.

I tried to go through `./build/bin/smpirun` and found that after the script in line number 245 `EXEC="$1"`, $EXEC was only `path/to/caffe_mpi/build/tools/caffe`

To test the possibility of fixing this issue by set $EXEC correctly, I manually edit the smpirun by adding 1 more script line:
`EXEC="${EXEC} train --solver=path/to/caffe_mpi/cifar10-test/solver.prototxt"` and it raised a problem 

> [0.000000] /SimGrid-3.19/src/surf/xml/surfxml_sax_cb.cpp:975: [xbt/CRITICAL] Unable to open 'train'

I think it caused by smpimain could not recognize the argument of the application (i.e., caffe)  in the script line
`${WRAPPER} "smpimain" ${EXEC} ${PRIVATIZE} ${TRACEOPTIONS} ${SIMOPTS} ${PLATFORMTMP} ${APPLICATIONTMP} <&3 3>&- &`

Do you have any idea on this issue?
Thank you

**Comment by adegomme** [comment]
I remember that a commit 3 months ago (see #287 ) allowed to pass -- to the command line in order to stop parsing simgrid arguments and use the app's one after. This was added in 3.21. It may have also fixed this behavior you're seeing. 
Could you try again with 3.21 or the latest git version ? With just the command line you tried, and if it still does not work, by trying to add -- (so "train -- --solver=path/to/cifar10-test/solver.prototxt" ) ?

**Comment by adegomme** [comment]
I just made a test locally with ( https://github.com/Caffe-MPI/Caffe-MPI.github.io  ) and I'm able to run things with an up-to-date simgrid .
I had to pass --cfg=smpi/privatize-libs:libgflags.so.2.2  (adapt the version to yours) option, though, to avoid issue with bad flags handling.

`smpirun -np 10 --cfg=smpi/privatize-libs:libgflags.so.2.2 -hostfile ~/simgrid/teshsuite/smpi/hostfile -platform ~/simgrid/examples/platforms/small_platform.xml --cfg=smpi/display-timing:1 --cfg=smpi/host-speed:1000000 ./build/tools/caffe train --solver=examples/cifar10/cifar10_quick_solver.prototxt`

**Comment by TruongThaoNguyen** [comment]
Thank you for your support. 
I also could make a test with Caffe-MPI with Simgrid version 3.21.

**Comment by mquinson** [comment]
Thanks for the follow up. I'm glad it fixed it.
