### ISSUE TITLE
Stacktrace: Avoid the backtrace variant of Boost.Stacktrace?

### ISSUE THREAD

**Issue by mpoquet** [simgrid/simgrid#320]
It seems that SimGrid uses Boost.Stacktrace since ~2018-10-29.
Is there a reason to use the backtrace variant of this library instead of another variant (e.g., addr2line)?

I think this variant will frustrate many users. The backtrace variant suffers from poor packaging (e.g., not in [arch](https://www.archlinux.org/packages/extra/x86_64/boost-libs/) nor nix default packages). This would not be a huge problem if compiling the library manually was straightforward, but this is not the case. [It only works with gcc](https://github.com/boostorg/stacktrace/issues/49), but even with it I still cannot compile it easily (my gcc is probably not packaged with dev headers such as backtrace.h).

**Comment by mquinson** [comment]
This was fixed recently: addr2line will be used as a fallback when found.
