### ISSUE TITLE
[S4U] Get task remaining work ratio

### ISSUE THREAD

**Issue by Mommessc** [simgrid/simgrid#321]
Hello there,

Being working on a definite switch from MSG to S4U in Batsim I've encountered problems with [`MSG_task_get_remaining_work_ratio`](https://github.com/simgrid/simgrid/blob/master/src/msg/msg_task.cpp#L202).

It looks like the function to use in S4U is [`Exec::get_remaining_ratio`](https://github.com/simgrid/simgrid/blob/master/src/s4u/s4u_Exec.cpp#L136) (or even directly [`ExecImpl::get_remaining_ratio`](https://github.com/simgrid/simgrid/blob/master/src/kernel/activity/ExecImpl.cpp#L71)).

Now the problem is I want the remaining ratio from an Actor calling [`parallel_execute`](https://github.com/simgrid/simgrid/blob/master/src/s4u/s4u_Actor.cpp#L299) and I am unable to see how I could do that, since I saw no way to access an Exec/ExecPtr from my Actor.

Is there a way to do that, or even is my way of trying correct but I am missing something important here?

Auxiliary question: would implementing a `parallel_execute` function in a similar way as for `exec_init`/`exec_async` that returns an ExecPtr be a solution?

**Comment by frs69wq** [comment]
About the auxiliary question, there is now way to start a parallel task in an asynchronous way. You can do
ExecPtr parallel_exec = simgrid::s4u::this_actor::exec_init(hosts, flops, bytes) 
and then one of these options:
  + exec->start(); /*whatever*/ exec->wait();
  + exec->start(); /*whatever*/ exec->wait_for(timetout);
  + exec->wait() // the call to start is hidden here
  + exec->waitfor(timeout) // the call to start is hidden here
 
I guess that you can also now call exec->get_remaining_ratio() even when there is a parallel task behind the ExecPtr. Could you please check whether the current version suits your needs and if so close the issue?

**Comment by Mommessc** [comment]
Apparently we finished to exterminate MSG to be fully with S4U on Batsim a few months back.
We now use `simgrid::s4u::this_actor::exec_init` and associated functions so I think everything is fine now since [this commit](https://github.com/simgrid/simgrid/commit/54f9d48567e65bd17b9ad3544b5aad57bef54463#diff-02d97bb643a1e585ab194d3041c08191).
