### ISSUE TITLE
Issue when an actor kills his host vm

### ISSUE THREAD

**Issue by AdrienGougeon** [simgrid/simgrid#322]
I suppose there is a bug when an actor inside a vm tries to kill its own host, i.e., the vm.
 
In the linked example there is two "vm->destroy();" pointing at the same vm. One is done by the master on another host, the other is done by an actor placed inside the vm

By commenting only one of the two you can see the differences:
- if killed by an actor from another host (here, the master) the load on the cpu induced by the actor placed in the vm is properly stopped and the vm do not appear anymore in the "simgrid::s4u::Engine::get_instance()->get_all_hosts()" vector.

- if killed by the actor inside the vm (life_cycle_manager) the load on the cpu induced by the actor in the vm is not stopped and the vm still appear in the "simgrid::s4u::Engine::get_instance()->get_all_hosts()" vector, but with the state "DESTROYED".

To use the example, unzip it and then execute: 
cmake .
make
./suicide_vm

**Comment by AdrienGougeon** [comment]
[suicide_vm.zip](https://github.com/simgrid/simgrid/files/2901364/suicide_vm.zip)

**Comment by agiersch** [comment]
As a first analysis, a call to "vm->destroy()" implicitly does a "vm->shutdown()" first.

When an actor wants to destroy its own VM, it's killed by the shutdown phase, and cannot finish the destruction.
