### ISSUE TITLE
S4U: Attempting to create an actor on turned off host segfaults instead of throwing

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#324]
Here is a tiny MWE that shows the problem. It looks like the inner-most function in SIMIX prints a warning when the host is off and returns nullptr, but the function above then de-references the pointer. 
[mwe_starting_actor_on_down_host.zip](https://github.com/simgrid/simgrid/files/2902410/mwe_starting_actor_on_down_host.zip)

**Comment by frs69wq** [comment]
The Actor::create method now raise a HostFailureException if the host given as parameter is off. Note that you can still have hosts starting as off in the deployment file. In this case, an extra warning would be displayed.
