### ISSUE TITLE
Valgrind-detected error for join() when energy plugin is activated

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#326]
After chasing down a complicated valgrind warning about a free memory write (that resulted in a segfault in WRENCH), I was able to produce a MWE for SimGrid. The MWE "works", but valgrind detects the free memory write. I haven't added it to teshsuite yet because I am not sure that's useful given that without valgrind there is no way (or it is unlikely) to detect the error.  So for now, I am attaching an MWE. Let me know if you want me to add it to the testsuite of course. 

It's  a very specific error: a join() with the energy plugin activated (i.e., if in the MWE you comment out the join() or the plugin activation, everything works)

[mwe_energy_and_join.zip](https://github.com/simgrid/simgrid/files/3026390/mwe_energy_and_join.zip)

**Comment by agiersch** [comment]
Hi,
I think that the plugin needs to be initialized before the platform is loaded.
Just call sg_host_energy_plugin_init() before engine->load_platform().

Valgrind seems happy with that, I'm thus closing the issue.

**Comment by henricasanova** [comment]
I am re-opening this issue, and attaching an update MWE that shows the valgrind error even though the call to sg_host_energy_plugin_init() is before the call to engine->load_platform(). 
[mwe_energy_and_join.zip](https://github.com/simgrid/simgrid/files/3031244/mwe_energy_and_join.zip)

**Comment by agiersch** [comment]
Does it help with the following patch? I seems good for the MWE.
@mquinson, do you foresee any problem without the simcall here?

```
--- a/src/s4u/s4u_Host.cpp
+++ b/src/s4u/s4u_Host.cpp
@@ -216,7 +216,7 @@ void Host::set_speed_profile(kernel::profile::Profile* p)
 /** @brief Get the peak processor speed (in flops/s), at the specified pstate  */
 double Host::get_pstate_speed(int pstate_index) const
 {
-  return simix::simcall([this, pstate_index] { return this->pimpl_cpu->get_pstate_peak_speed(pstate_index); });
+  return this->pimpl_cpu->get_pstate_peak_speed(pstate_index);
 }
 
 /** @brief Get the peak computing speed in flops/s at the current pstate, NOT taking the external load into account.
```

**Comment by agiersch** [comment]
Even better: swapping the calls to set_state() and set_remains() in Action::finish() should do the trick.
Can you please test this?
```
--- a/src/kernel/resource/Action.cpp
+++ b/src/kernel/resource/Action.cpp
@@ -47,8 +47,8 @@ Action::~Action()
 void Action::finish(Action::State state)
 {
   finish_time_ = surf_get_clock();
-  set_state(state);
   set_remains(0);
+  set_state(state);
 }
 
 Action::State Action::get_state() const
```

**Comment by henricasanova** [comment]
I tested both patches and they both work!  The second is   very clear and, in hindsight, obvious ;) I cannot believe that has never caused a problem before.

**Comment by mquinson** [comment]
+1 How could it not be detected until now? Kudos to @agiersch for diagnosing this!
