### ISSUE TITLE
Missing links on dragonfly example svg

### ISSUE THREAD

**Issue by zlsh80826** [simgrid/simgrid#335]
Hello,
I found there are missing links on dragonfly example svg on the [MPI tutorial](https://simgrid.org/doc/latest/Tutorial_MPI_Applications.html) (also the [platform example](https://github.com/simgrid/simgrid/blob/master/examples/platforms/cluster_dragonfly.svg))

I think there should be two links between blade 0 of chassis 1 and 2 in group 1, like the redline of the attached file.
![cluster_dragonfly_modified](https://user-images.githubusercontent.com/14275056/72098079-bda3f900-3358-11ea-8f79-4124058dc074.png)

**Comment by adegomme** [comment]
This is indeed right. Thanks for the report. 
Fixed in 41b9de5d (not synchronized yet on github, but available on framagit)

**Comment by zlsh80826** [comment]
OK, thank you !

**Comment by mquinson** [comment]
Fixed in https://github.com/simgrid/simgrid/commit/41b9de5d0009f329d408d9ba05a946f4a49b879d thus closing.
