### ISSUE TITLE
Changing platform bandwidth config has no effect in simulation

### ISSUE THREAD

**Issue by Ricahrd-Li** [simgrid/simgrid#338]
Hi guys, 
I am using simgrid to simulate baidu ring-allreduce alg ([baidu-allreduce github link here](https://github.com/baidu-research/baidu-allreduce)) , which mainly uses ``MPI_Irecv``, ``MPI_Send``,``MPI_Wait``,``MPI_Allgather`` and ``MPI_Sendrecv``. 

From the latest doc of simgrid I learned that I can config my dream platform in XML for simulation, and I just choose a very simple network topology ``cluster_crossbar.xml`` in practice. 

However, when I change the bandwidth in  ``cluster_crossbar.xml`` from very high to extremely low, I find that the output ring allreduce time is almost the same (the very low bandwidth platform even faster sometimes!)  See detailed log below.

---
The command I run:
```
smpirun -np 4 -trace-ti -platform ./cluster_crossbar.xml -hostfile cluster_
hostfile --cfg=smpi/display-timing:yes  --cfg=tracing/filename:R
INGALLREDUCE --cfg=smpi/host-speed:40000000 ./ringallreduce > logfile_name 
```
hostfile:
```
node-0.simgrid.org
node-1.simgrid.org
node-2.simgrid.org
node-3.simgrid.org
```
---
High bandwidth:
```
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4.1">
  <zone id="world" routing="Full">
    <cluster id="cluster-crossbar" 
             prefix="node-" radical="0-100" suffix=".simgrid.org"
	     speed="40Gf" bw="20MBps" lat="50us"/>
  </zone>
</platform>
```
part of output
```
Verified allreduce for size 8388608 (0.427333 per iteration)
Verified allreduce for size 16777216 (0.838939 per iteration)
Verified allreduce for size 33554432 (1.88878 per iteration)
Verified allreduce for size 67108864 (4.38438 per iteration)
Verified allreduce for size 134217728 (9.53242 per iteration)
```
---
Very low bandwidth:
```
  <zone id="world" routing="Full">
    <cluster id="cluster-crossbar" 
             prefix="node-" radical="0-100" suffix=".simgrid.org"
	     speed="40Gf" bw="0.0002MBps" lat="50000us"/>
  </zone>
```
part of output
```
Verified allreduce for size 8388608 (0.4115 per iteration)
Verified allreduce for size 16777216 (0.866905 per iteration)
Verified allreduce for size 33554432 (2.1426 per iteration)
Verified allreduce for size 67108864 (4.36098 per iteration)
Verified allreduce for size 134217728 (10.3441 per iteration)
```

You can see that changing bandwidth in platform xml has no effect, but in baidu-allreduce alg communication takes near 25% of the total time. So I am very confused. 
Appreciate your reply, thanks.

**Comment by adegomme** [comment]
Hi,

trying to reproduce here (had to find a cuda-compatible machine to compile, even if in the end it's not really useful).. and I don't think there's an issue on our end. I can see timings increasing greatly when changing values in the platform file ( with --log=smpi_mpi.:debug to see mpi calls) . 
I see that you used --cfg=smpi/display-timing:yes  .. What does it say in the end ?

I will update this post as soon as I have results on my end.

**Comment by Ricahrd-Li** [comment]
Sorry for the late reply, just saw your post. 
Sorry for not mentioning earlier that for Baidu allreduce alg I pass 'cpu' as the arg, therefore it will only use cpu for calculation.

by using `` --cfg=smpi/display-timing:yes``, at the end it says:

---
High bandwidth
```
Verified allreduce for size 16777216 (0.859017 per iteration)
Verified allreduce for size 33554432 (1.85981 per iteration)
Verified allreduce for size 67108864 (3.51882 per iteration)
Verified allreduce for size 134217728 (11.6731 per iteration)

[1408.719939] [smpi_kernel/INFO] Simulated time: 1408.72 seconds. 
The simulation took 293.759 seconds (after parsing and platform setup)
228.109 seconds were actual computation of the application
[1408.719939] [smpi_kernel/INFO] More than 75% of the time was spent inside the application code.
You may want to use sampling functions or trace replay to reduce this.
```
---
Low bandwidth: (I reran it just now)
```
Verified allreduce for size 16777216 (1.00057 per iteration)
Verified allreduce for size 33554432 (2.18769 per iteration)
Verified allreduce for size 67108864 (4.71661 per iteration)
Verified allreduce for size 134217728 (12.719 per iteration)

[140018104.453332] [smpi_kernel/INFO] Simulated time: 1.40018e+08 seconds. 
The simulation took 333.112 seconds (after parsing and platform setup)
244.656 seconds were actual computation of the application
```
I see that in low bandwidth situation, the ``Simulated time`` becomes really long(``1.40018e+08 seconds``), but in the output log, the ring allreduce time per iteration is quite close to which in high bandwidth situation, which is weird. 

Your result makes sense, and did you use GPU?  Is it the case that you just modify the ``cluster_crossbar.xml`` and rerun the same command to get the result? Thx!

**Comment by adegomme** [comment]
I did not actually use the GPU, I just had to have CUDA to compile everything, but I used "cpu" at execution time in the end.

I think the issue might be the timing function you are using, which may do "real" timing, and not using "simulated" timing, thus reporting bad timings in your log (but trace and total simulation time will be correct. 
If we simulate in 0.1 second an event/communication that would take 100 seconds, we want timing functions to report we spent 100 seconds in it, and not the real 0.1s.

We try to intercept calls to gettimeofday and clock_gettime to use simulated times, though, so it should work in most cases. But it looks like that in your it may not use the correct one (the code seems to use clock_gettime, though..). Could you please send the output of
"nm ringallreduce | grep clock" ? it should call smpi_clock_gettime and not clock_gettime if everything went smoothly

If it does not, it means that it failed to override the call (check include/smpi/smpi_helpers.h to see what it does, it's only activated if it can find 
`_POSIX_TIMERS` when compiling).
Did you use smpicxx to compile ? It is performing this operation normally.

A way to overcome this is to use MPI_Wtime instead of your own timing solution, as this one always reports the simulated time with SMPI.

**Comment by Ricahrd-Li** [comment]
the output of ``nm ringallreduce | grep clock`` is 
```
U clock_gettime@@GLIBC_2.17
```
It's true it doesn't use ``smpi_clock_gettime``. But I have used ``smpicxx`` for compiling. 
I will check out ``MPI_Wtime``, and I will update this issue if I get some results. thanks a lot!!!

**Comment by adegomme** [comment]
I checked that in my case it's using smpi_clock_gettime properly, so this is the issue, indeed.

**Comment by Ricahrd-Li** [comment]
After replacing ``rdtsc()`` (which I originally used to get time) with ``MPI_Wtime()``, the output time log works well, and after changing bandwidth in platform config file, I can clearly see the change of simulated time, and the result makes sense. 
Really Appreciate it! @adegomme
