### ISSUE TITLE
Questions about some parts of the latest doc of simgrid 

### ISSUE THREAD

**Issue by Ricahrd-Li** [simgrid/simgrid#340]
Hi guys, 
I am a user of SMPI,  and my friend and I are simulating a ring-allreduce alg on our local machine to predict its performance on a bigger cluster using SMPI. 

When simulating our program, to make the simulation result as accurate as possible, we have read your latest doc of simgrid and smpi detailedly. (from [this site](https://simgrid.org/doc/latest/))

When reading the doc, I am confused by some concepts and have some questions, which are as follows.
1. **About "Concurrency Limit"  config** [(site link)](https://simgrid.org/doc/latest/Configuring_SimGrid.html#cfg-maxmin-concurrency-limit) : What are the "resources" mentioned here in practice? Is it the case that different concurrency limit settings will affect the result of the simulation, even on the same local machine? 

2. **About "bandwidth factor" config** [(site link)](https://simgrid.org/doc/latest/Configuring_SimGrid.html#bandwidth-factors): what is the unit of the bandwidth in this section? and the reason why this is important is that bandwidth config plays a critical role in network communication simulation.

3. **About mpi implementation** 
In section 2.4 "_SMPI: Ad-hoc Virtualization of MPI Applications"_ of the paper " _Simulating MPI applications: the SMPI approach._" on _IEEE Transactions on Parallel
and Distributed Systems_, you mentioned that "_SMPI is based on a complete implementation of the MPI standard on top of the SimGrid simulation kernel_", and I want to ask do you hand-rewrote the mpi codes or you transfer existing mpi codes into SimGrid? If the latter one is the case, which version of mpi do you use?  

Any of your insight is appreciated!

**Comment by adegomme** [comment]
Hi,

I will start by answering the last question. 

- SMPI is mostly written from scratch, with some exceptions. The main one is collective communications, where to be more realistic, we had to switch our basic "default" collective operations for the decision logic and implementations of the collective operations from existing MPI implementations (not the latest versions anymore, an update would be good). You can see the list of available algorithms/selectors in SMPI in https://simgrid.org/doc/latest/app_smpi.html#simulating-collective-operations 
You might be interested in https://simgrid.org/doc/latest/app_smpi.html#mpi-allreduce for example.
Code for selectors (to emulate behavior on a particular MPI implementation) and individual algorithms these can be found in src/smpi/colls folder is simgrid.

- The bandwidth factor (and latency) don't have units, as they are the represent the portion of the nominal bandwidth that can be reached for messages this size (0.5 would be half of the nominal bw). To provide the most accurate simulation, they can be measured experimentally on existing clusters (check the link to the platform-calibration repository. But this might be a bit outdated, so getting good results can be tricky).

- The concurrency limit is very much internal to the simgrid engine, I don't think you should touch it. Simgrid simulates shared resources (links, computing resources) with a maxmin solver (lmm), which is the core of simgrid. The documentation of simgrid is being rewritten slowly, so this does not appear yet on the new website, but you can find here an older description :
http://simgrid.gforge.inria.fr/simgrid/3.20/doc/group__SURF__lmm.html
The main use for concurrency limit was to ease simulation when thousands of actors were competing for a single resource (think thousands of messages sent simultaneously through the same network link), which could stress the simulation engine a little bit too much and make it really slow. Limiting this value would mean serializing some messages (which can be a realistic behavior) so they would have to wait for the system to get less congested. 
But the issue with the setting  you're asking about is that it's a global setting, so it would apply the same behavior to all resources in simgrid, and that's not really great. Leaving it as such is a good idea. Maybe it can be set internally in some models if needed, but that would be only in the case you want to play with internals of simgrid's engine (to add new routing, new network models or new cluster types).  
If I said something incorrect, please correct me, other people :p

**Comment by mquinson** [comment]
This all seems very good to me, I couldn't say it in a better way :)

**Comment by Ricahrd-Li** [comment]
Thanks for your reply!
One thing that I don't quite get is that, in the description below, what is the unit of message size? like in "65472:0.940694", what is the unit of "65472"? Do you mean that if I set bandwidth to be 100Gbps, the the unit of "65472" will be "Gb"? Thanks. 
```
Option smpi/bw-factor
Default: 65472:0.940694;15424:0.697866;9376:0.58729;5776:1.08739;3484:0.77493;1426:0.608902;732:0.341987;257:0.338112;0:0.812084
```

**Comment by adegomme** [comment]
The message size is always in bytes here, I will add that in the doc.

**Comment by Ricahrd-Li** [comment]
Gotcha, thanks a lot!

**Comment by mquinson** [comment]
Closing the bug since the doc was improved to address this concern.
Please feel free to reopen on need.
