### ISSUE TITLE
Silent error when linking of C++ class files

### ISSUE THREAD

**Issue by sampollard** [simgrid/simgrid#342]
Hi everyone. I'm excited to use SimGrid because it's exactly what I need for my research! I'm really impressed you can emulate the MPI operations for so many different MPI implementations on so many topologies.

However, I ran into a bug in your linking phase (or something, I'm not sure). Here are the steps to reproduce:

This was found with SimGrid version 3.25. Suppose we have 3 files:
`class.hpp`
```
#include <iostream>
using namespace std;

class Foo {
    public:
        Foo();  // Empty constructor
        Foo(int n);
    private:
        int n_;
};
```

`class.cpp`:
```
#include "class.hpp"

Foo::Foo(int n) : n_(n) {
	cout << "Initialized n_ to " << n << endl;
}
// SILENT ERROR! I did not provide a constructor with 0 arguments
```

`main.cpp`:
```
#include <iostream>
#include "class.hpp"
using namespace std;
int main()
{
    Foo f;
    cout << "Why does this fail?" << endl;
}
```

And execute the commands:
```
smpicxx -c class.cpp
smpicxx -c main.cpp
smpicxx -o main main.o class.o
```
These have no errors. Though, when running, we get a core dump (or in other cases, I will take the error from my example that I simplified):
```
/home/users/spollard/.local/lib/simgrid/smpimain: symbol lookup error: ./dotprod_mpi_56182_0.so: undefined symbol: _ZN16random_kary_treeC1Ev
```
Where
```

$ c++filt _ZN16random_kary_treeC1Ev
random_kary_tree::random_kary_tree()
```
(the empty constructor that I forgot to add `{ }` to in my actual code!)

This is unwanted, because with OpenMPI's `mpicxx` version 3.1.5 and `g++` version 7.5.0, I get the following error:
```
main.cpp:(.text+0x1f): undefined reference to `Foo::Foo()'
```

**Comment by adegomme** [comment]
Hi, and welcome to SimGrid
I think your issue is due to the fact that smpi actually silently generates a shared library instead of an executable when using the wrappers. This is due to the privatization techniques we are using later, using dlopen on this shared library. 
A side effect of this (adding -shared to gcc flags) is indeed that missing symbols are allowed at link time and not caught before execution.
I will check if we can provide some options to the linker(s) to add such a check without breaking too many things.

**Comment by adegomme** [comment]
I can confirm that adding -Wl,-z,defs to our link flags in the wrappers works on a linux+gcc+ld system and provide the missing checks
main.cpp:(.text+0x23): undefined reference to `Foo::Foo()'
It's currently being tested on other platforms to see if fails.

**Comment by adegomme** [comment]
@sampollard could you confirm the version on the trunk works for you?

**Comment by sampollard** [comment]
It works! I get the expected error `undefined reference to `Foo::Foo()'`

I built on commit 21b95ecfa0911d6ca87668482b11ab9498edd8f3

Thank you very much

**Comment by mquinson** [comment]
btw @sampollard if you want to come and chat with us, we use IRC on channel #simgrid of the OFTC network. e.g. the server irc.debian.org
Since most of us are native french speaker we tend to not always speak english, but we switch when having non-french speaking visitors.
Hope to see you there,
Mt
