### ISSUE TITLE
Wrong consumed energy when an exec timeouts

### ISSUE THREAD

**Issue by Mommessc** [simgrid/simgrid#343]
Hello,

As a Batsim user reported [here](https://github.com/oar-team/batsim/issues/51) there seem to be a problem when an Exec on multiple hosts timeouts.
It looks like only the first host was considered computing while others were idle until the timeout.

I created a MWE [here](https://gist.github.com/Mommessc/5b5c846b02e7c456c584bfc105ba8ede).
There are 4 (single-core) hosts with a consumption of 1 W when idle and 50 W when computing.

In the MWE an actor creates successively 3 identical Exec with different timeouts options and reports the energy consumption of each host during the executions.

Exec1 computes during 1 second on 3 hosts without timeout.
The energy consumption is 50 J as expected for the 3 hosts, while the 4th host consumes 1 J.

Exec2 computes the same thing but timeouts after 0.99 s.
The energy consumption of the first host is as expected (0.99*50 J) but not for the 2 other hosts that computed. They were considered idle and consumed only 0.99*1 J.

Exec3 computes the same thing but timeouts after 1 s (notice here that the computation should have completed successfully after 1 s).
However the energy consumptions are the same as for Exec1 which did not time out.

**Comment by frs69wq** [comment]
Fixed by 0779d3a082

**Comment by Mommessc** [comment]
I guess it's commit e1d5724, thanks!
