### ISSUE TITLE
Unable to Parse xml straight from examples/platforms

### ISSUE THREAD

**Issue by Adlabz** [simgrid/simgrid#348]
Using platform straight from the examples produces the output below. This looks similar to this issue from [2016](https://lists.gforge.inria.fr/pipermail/simgrid-user/2016-March/003929.html). However, I am using an example from the repo, and I have also run simgrid_update_xml.pl on it and the xml is conformant to 4.1, so it should be a no-op.

To be honest, I'm an undergrad student and I'm using SimGrid for the first time so it might also just be me not knowing what I'm doing. Running on Ubuntu 16.04 if that helps.

```
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'

[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'

Invalid XML (XML input line 2, state 2): Bad declaration <!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">.

If your are using a XML v3 file (check the version attribute in <platform>), please update it with tools/simgrid_update_xml.pl

[0.000000] /build/simgrid-5f28qY/simgrid-3.18+dfsg/src/surf/xml/surfxml_sax_cb.cpp:49: [surf_parse/ERROR] Parse error at wifi.xml:2: Parse error in wifi.xml

[0.000000] /build/simgrid-5f28qY/simgrid-3.18+dfsg/src/surf/xml/surfxml_sax_cb.cpp:51: [xbt/CRITICAL] Exiting now
./combined --cfg=smpi/privatization:1 --cfg=surf/precision:1e-9 --cfg=network/model:SMPI wifi.xml smpitmp-appELcWZi

Generated hostfile smpitmp-hostfHUoue5 kept.

Execution failed with code 134.
```

Also I found a typo: "If you are using an XML v3 file", not "If your are using a XML v3 file" :)

**Comment by mquinson** [comment]
Could you please tell us the version of simgrid that you are using, and also post your faulty platform file?

If it's a git checkout, please refresh it, a similar issue was fixed last week.

Bye, Mt
-- 
Envoi mobile. Veuillez excuser ma brièveté.

**Comment by Adlabz** [comment]
Simgrid 3.18
File is wifi.xml (although I've tried a bunch of the examples: torus, cluster with backbone, etc) and all have the same problem
[wifi.txt](https://github.com/simgrid/simgrid/files/5371931/wifi.txt). Uploaded as txt because git doesn't support uploading XMLs here.

Thanks

**Comment by mquinson** [comment]
Your version is 3 years old, that's a lot :) 
If I'm correct, you are trying to use a platform of a recent release with an old release. I would have thought that it should work, but since you report that it doesn't, then you should not do that. Instead, please update your simgrid version to match the version in which you find the platform files.

I think that the error message that you get simply means that: please don't use platform files from the future.
Can you tell us whether updating your simgrid actually fixes the issue?

Thanks for reporting, 
Mt

**Comment by Adlabz** [comment]
Whoops, using a more recent version, ça a marché. Thank you!
