### ISSUE TITLE
after pip install simgrid, i cannot import simgird

### ISSUE THREAD

**Issue by tyn513** [simgrid/simgrid#386]
hi,
      i am trying to install your simgrid on MAC os. However, after pip install simgrid, i cannot import simgird. Is there a way out?

![image](https://user-images.githubusercontent.com/19583397/230267784-f820efae-56ff-4733-8f1e-456a95256bb2.png)

**Comment by adegomme** [comment]
not sure with anaconda, but I just tried and was able to make it work with pip in a venv.


Your 'no module found' would suggest that your site-packages folder is not in PYTHONPATH 
you can check search path with import sys ; print (sys.path), to see if something is missing there

You may want to try to remove/reinstall the simgrid package? and be sure to have the dependencies installed first for the build (This package contains a native library. Please install cmake, boost, pybind11 and a C++ compiler before using pip3. On Debian/Ubuntu, this is as easy as sudo apt install cmake libboost-dev pybind11-dev g++ gcc )


I needed to put the path to libsimgrid.so in LD_LIBRARY_PATH, though, which is not ideal. 

```
apt install -y cmake libboost-dev pybind11-dev g++ gcc
apt install -y python3-full python3-dev
python3 -m venv test
source test/bin/activate
pip install simgrid
export LD_LIBRARY_PATH=$PWD/test/lib/python3.11/site-packages:$LD_LIBRARY_PATH
python .. and import simgrid showed 
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'contexts/factory' to 'thread'
```

**Comment by tyn513** [comment]
> 

hi, thx for your reply.

I also tried to build from source code， but I still failed to install.
However, i successfully install it on ubuntu.  Is that means simgrid cannot be used on M1/M2 MAC?

**Comment by adegomme** [comment]
that's indeed a platform we don't have hardware to test for, so it may break. Can you send the build log ?

**Comment by tyn513** [comment]
> that's indeed a platform we don't have hardware to test for, so it may break. Can you send the build log ?

I solved it by docker. Thanks for your support.
Actually, it works only when I use apt-get install python-simgrid. Otherwise, I cannot import it through python.
