### ISSUE TITLE
may i ask：is there a way or interface in simgrid to combine gem5 with your simgrid

### ISSUE THREAD

**Issue by tyn513** [simgrid/simgrid#387]
may i ask：is there a way or interface in simgrid to combine gem5 with your simgrid?

**Comment by mquinson** [comment]
Hello,
AFAIK, nobody ever tried to interface simgrid and gem5. We interfaced simgrid with a plenty of simulators (ns-3, openmodelica, etc), but never with gem5 so far. It must be doable however, and we could maybe provide some guidance if you're willing to be the first to ever interface these two simulators. If so, come and discuss with us on [mattermost](https://framateam.org/simgrid/channels/dev-en).

Thanks for your interest,
Mt
