### ISSUE TITLE
_simgrid_log_category__default' was not declared in this scope

### ISSUE THREAD

**Issue by DonAurelio** [simgrid/simgrid#397]
#### Reproducer
```c++
#include <xbt/log.h>
#include <simgrid/version.h>

int main(int argc, char *argv[]) {
    XBT_INFO("SimGrid version: %d.%d.%d", SIMGRID_VERSION_MAJOR, SIMGRID_VERSION_MINOR, SIMGRID_VERSION_PATCH);
    return 0;
}
```
#### Output
```
error: '_simgrid_log_category__default' was not declared in this scope; did you mean '_simgrid_log_category__xbt'?
```
#### Environment
* Compile: g++ reproducer.cpp -lsimgrid
* Ubuntu 24.04, Docker Container, executed as root user.
* SimGrid version: 3.35.0

#### Observations
I believe the `_simgrid_log_category__default` category is created at runtime, but to compile `XBT_INFO`, `_simgrid_log_category__default` must already exist.

#### Workaround

```g++
#include <xbt/log.h>
#include <simgrid/version.h>

/* Workaround since the default category does not work. */
XBT_LOG_NEW_DEFAULT_CATEGORY(category, "description");

int main(int argc, char *argv[]) {
    XBT_INFO("SimGrid version: %d.%d.%d", SIMGRID_VERSION_MAJOR, SIMGRID_VERSION_MINOR, SIMGRID_VERSION_PATCH);
    return 0;
}
```

**Comment by mquinson** [comment]
Hello, you probably want to read https://simgrid.frama.io/simgrid/The_XBT_toolbox.html#logging-api

In short, you want to add XBT_LOG_NEW_DEFAULT_CATEGORY or another similar macro.
