### ISSUE TITLE
simgrid_full.jar broken on Mac OSX

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#5]
simgrid_full.jar contains the native libraries so that you can use SimGrid as if it were a pure Java library. We need to embeed both libsimgrid and libsimgrid-java. (side note: that's split to allow the construction of two binary packages on Debian, allowing the users to depend on java only if they need it).

The trick is that at startup, we try to load the libraries on disk, and if not found, we use the ones included in the jar file. That's done here: https://github.com/mquinson/simgrid/blob/master/src/bindings/java/org/simgrid/NativeLib.java#L37

On some operating systems, we load the lib directly from the jarfile (from memory), but some other operating systems (Mac OSX) forbid it. As a result, we have to write it on disk before loading it. We do so in a temporary directory, and we clean it automatically at shutdown. All this is the purpose of the loadLib function, here: https://github.com/mquinson/simgrid/blob/master/src/bindings/java/org/simgrid/NativeLib.java#L72

To complicate the debug, our testing infrastructure is not good on Mac OSX. http://ci.inria.fr/ does not provide any Mac daemon at the current time. Travis says to be at capacity for this arch and does not accept any new project on that arch. We only have one machine located in Nancy on which we can test. A cron table still pushes the results to http://cdash.inria.fr/CDash/index.php?project=SimGrid but it sometimes fails for other reasons.

That is why we didnt detect earlier that we get the following warning at config time:

  CMake Warning (dev):
    Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
    --help-policy CMP0042" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.

```
MACOSX_RPATH is not specified for the following targets:

 simgrid
 simgrid-java
```

  This warning is for project developers.  Use -Wno-dev to suppress it.

The meaning of this warning is given here: http://www.cmake.org/Wiki/CMake_RPATH_handling#Mac_OS_X_and_the_RPATH In short, that because libraries contain the full path to their dependencies on Mac. I guess that it's to allow the installation of several version of the same library, similarly to Gentoo multihoming. Even if that functionality may be good for users in general, it breaks our trick of unpacking the native lib to a temporary path before loading it.

The cmake link above explains that we have to choose how we want to install our libs, depending on how our application will use them, and provides several configuration flavors. At the end, the fix should be easy, as it was done for another project here: https://github.com/Nuand/bladeRF/commit/58d4870221f79f82944aa6bcc78ecf1191a61622

The Java tests on that build daemon seem to work, even if they are marked broken because of debug messages about the locations of native libraries loaded. (side note: I fail to see where they are produced, which bugs me). It seems to me that we are testing against the simgrid_full library and not the simgrid.jar one (https://github.com/mquinson/simgrid/blob/master/buildtools/Cmake/AddTests.cmake#L526) so I guess that the thing is finding the external libs and not trying to use the internal ones. I'm not sure of how to make our test more robust here.

So we have several bugs here:
- RPATH not set in a way that allows simgrid_full (and I dunno how to do that yet)
- debug messages breaking the tests for nothing
- Testing infrastructure not robust to the fact that simgrid_full gets unable to load internal libs

**Comment by randomstuff** [comment]
If I understood correctly, the issue is related to the fact that `libsimgrid-java` depends on `libsimgrid` and `libsimgrid-java` cannot resolve `libsimgrid` (probably because the dependency between the two libs id defined using a @rpath/ based path and the location we're copying the file is not in the RPATH).

**Comment by randomstuff** [comment]
In this case, I see multiple solutions :

1. Create a "full_jar" cmake option. If this options is specified, the build process will build the full jar. Otherwise, it will create the non-full jar. In the full_jar mode, we create a single shared library (instead of splitting libsimgrid and libsimgrid-java). This will fix the issue of resolving the second shared library.

2. Use a  `@load_path/` dependency when copying the dylib in the JAR.

**Comment by mquinson** [comment]
If you ask me, the first approach seems much more interesting: this simplifies things, and should thus improve the overall robustness. The second approach is specific to [this version] of the considered operating system.

**Comment by randomstuff** [comment]
Related [issue](https://gforge.inria.fr/tracker/index.php?func=detail&aid=17649&group_id=12&atid=165): 

> It seems that the problem with rpath is still present (at least under mac os X)
When I'm launching a simgrid simulation written in Java and by leveraging only the simgrid_full.jar (i.e. the one available on the website: https://gforge.inria.fr/frs/download.php/file/33700/simgrid-3.11.1.jar ) . I'm getting an issue related to the impossibility to load the library:

> ...dlopen(/private/var/folders/vv/fd14mcwn6g97bjbl79gg7kyw0000gn/T/simgrid-java-9158583498233713508.tmp, 1): Library not loaded: /Users/simgridtest/simgrid/lib/libsimgrid.3.11.dylib
Referenced from: /private/var/folders/vv/fd14mcwn6g97bjbl79gg7kyw0000gn/T/simgrid-java-9158583498233713508.tmp
Reason: image not found
....

**Comment by randomstuff** [comment]
I looked a bit this topic and I have the feeling that the second solution might be better in the long term. Currently, it might work because libsimgrid does not have any `-l` library dependency (in the standard, non-MC-mode, non -NS3, non-LTTNG) except system libraries (libc, libstdc++, libm, libgcc_s, libpthread, librt on Linux). We have dependencies on boost, but currently they are purely header-based (we do not link against boost `.so` or `.a`).

If we try to link against additional library, we will have two choices:

1. do not include them into the unique so/dyli (and we still have to solve the issue of having the dynamic linker find them);

2. include them in the so/dylib as well.

This second point is not as convenient at it may seem: for example on Linux systems, we sometimes have already packaged `.a` static libraries or have the option to build them but they are usually built non-<abbr title="Position Independent Code">PIC</abbr> and on some target (such as x86_64 Linux), we cannot link normal non PIC code into shared objects which means we'd have to rebuild each dependency in PIC static library:

~~~
$ gcc f.c -c -o f.o -fPIC
$ gcc f.c -c -o f.o
$ $ gcc foo.o f.o -shared -o foo.so
/usr/bin/ld: f.o: relocation R_X86_64_PC32 against symbol `g' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
~~~

I guess, there might be additional issues (in case of `dlsym` usage, constructor/destructors).

**Comment by randomstuff** [comment]
So I tend to thinks that we might try using this solution:

1. add an rpath/runpath entry to libsimgrid-java.so and/or libsurf-java.so (with some syntactic differences, this works with both ELF-based OSes and Mac OS X);

2. on MacOS X, set the install names to include the rpath;

3. modify the Java code which extract the nativ lib in order to create a temporary directory and copy all the native libraries with there suitable real names.

On Windows, only (3) will be used.

This solution should work with ELF-based OSes, MacOS X and Windows.

On MasOS X, if we start shipping thirs party dylib in the JAR, we might have to force them to change the install names of their dependencies before bundling them in the JAR but it should be quite straightforward.

**Comment by mquinson** [comment]
I would prefer to use the libs in memory (instead of unpacking them on disk before use) if possible, but I do understand that this may not be robust. We rely on the fact that the JVM is cleaver enough to do the Right Thing on all architectures.

A probably opposed goal is the good old KISS. We should try to use the simplest and thus robust way. Under that criteria, unpacking the libs may be the right way to go...

Unsure, sorry.

**Comment by randomstuff** [comment]
We have this (related) cmake warning on MacOS X:

<pre>CMake Warning (dev):
   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
   set the policy and suppress this warning.

   MACOSX_RPATH is not specified for the following targets:

    simgrid

 This warning is for project developers.  Use -Wno-dev to suppress it.
</pre>

**Comment by randomstuff** [comment]
Currrently what I get is this:

<pre>$ DYLD_PRINT_LIBRARIES=1 java -cp simgrid_full.jar:examples/java suspend.Suspend ../examples/platforms/platform.xml ../examples/java/suspend/suspendDeployment.xml
[...]
dyld: loaded: /private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-6692010764153137712.tmp
dyld: loaded: /usr/local/lib/libboost_context-mt.dylib
dyld: loaded: /usr/local/lib/libboost_chrono-mt.dylib
dyld: loaded: /usr/local/lib/libboost_thread-mt.dylib
dyld: loaded: /usr/local/lib/libboost_system-mt.dylib
dyld: loaded: /private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp
dyld: unloaded: /private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp: dlopen(/private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp, 1): Library not loaded: /Users/ci/simgrid/build/lib/libsimgrid.3.12.dylib
  Referenced from: /private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp
  Reason: image not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.simgrid.NativeLib.loadLib(NativeLib.java:96)
        at org.simgrid.NativeLib.nativeInit(NativeLib.java:40)
        at org.simgrid.msg.Msg.nativeInit(Msg.java:20)
        at org.simgrid.msg.Msg.<clinit>(Msg.java:25)
        at suspend.Suspend.main(Suspend.java:14)
</pre>

This is what happens on the CI machine:

* it first loads `/private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-6692010764153137712.tmp` (this is a copy of `libsimgrid.3.12.dylib`)
* it loads its dependencies
* it then laods `/private/var/folders/w0/nn_htp7n6ddcydvkv21hjzhc0000gn/T/simgrid-java-3789259524132996711.tmp`
* it load its dependencies which includes `/Users/ci/simgrid/build/lib/libsimgrid.3.12.dylib`
* it tries to load `libsimgrid.3.12.dylib` a second time (it is already loaded) and fails.

**Comment by randomstuff** [comment]
Hardcoded path to libsimrid in libsimgrid-java:

<pre>$ otool -L lib/libsimgrid-java.3.12.dylib
lib/libsimgrid-java.3.12.dylib:
	libsimgrid-java.3.12.dylib (compatibility version 0.0.0, current version 3.12.0)
	/Users/ci/simgrid/build/lib/libsimgrid.3.12.dylib (compatibility version 0.0.0, current version 3.12.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/local/lib/libboost_context-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
</pre>

**Comment by mquinson** [comment]
If I understand correctly, the direct dependency from libsimgrid-java onto libsimgrid seems to hurt more than it helps (we are loading both libraries manually anyway). This dependency is declared here:
https://github.com/mquinson/simgrid/blob/master/buildtools/Cmake/MakeJava.cmake#L28

You could try to remove that dep and see if (1) it still works in other settings (2) it helps with embeeded libraries on mac, maybe.

**Comment by mquinson** [comment]
@alebre could you please test whether the current simgrid.jar works on Mac OSX, please?

**Comment by alebre** [comment]
current you mean the last one from the trunk ? or the last one available on the website ?

**Comment by mquinson** [comment]
The one from trunk, at least. And both if possible :)

Thanks in advance

**Comment by alebre** [comment]
[vm-0:Daemon:(3) 0.000000] /Users/alebre/DEVELOPMENTS/simgrid/src/xbt/exception.cpp:45: [xbt_exception/CRITICAL] Uncaught exception xbt_ex by Daemon/3: Gasp! This exception may be lost by subsequent calls.
[vm-0:Daemon:(3) 0.000000] /Users/alebre/DEVELOPMENTS/simgrid/src/xbt/exception.cpp:80: [xbt_exception/CRITICAL] Current backtrace:

Process finished with exit code 134

The one with the trunk :(
The one from the 3.13 is ok.

**Comment by mquinson** [comment]
@alebre and what about this one?
https://ci.inria.fr/simgrid/job/SimGrid-Multi/build_mode=Debug,node=simgrid-osx-mavericks/lastSuccessfulBuild/artifact/build/SimGrid-3.13.90/build/simgrid.jar
Thanks, Mt.

**Comment by alebre** [comment]
Cannot load the bindings to the simgrid-java library in path NATIVE/Darwin/amd64/ and no usable SimGrid installation found on disk.
Try to install the missing dependencies, if any. Read carefully the following error message.

java.lang.UnsatisfiedLinkError: /private/var/folders/p0/r77_8vgn3mj0cnt032n6pmyh0000gn/T/simgrid-java-6877511999523621239/libsimgrid-java.dylib: dlopen(/private/var/folders/p0/r77_8vgn3mj0cnt032n6pmyh0000gn/T/simgrid-java-6877511999523621239/libsimgrid-java.dylib, 1): Symbol not found: __ZN7simgrid6kernel7context14ContextFactory14create_maestroENSt3__18functionIFvvEEEPNS_5simix9ActorImplE
  Referenced from: /private/var/folders/p0/r77_8vgn3mj0cnt032n6pmyh0000gn/T/simgrid-java-6877511999523621239/libsimgrid-java.dylib
  Expected in: /usr/local/lib/libsimgrid.3.13.90.dylib
 in /private/var/folders/p0/r77_8vgn3mj0cnt032n6pmyh0000gn/T/simgrid-java-6877511999523621239/libsimgrid-java.dylib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.simgrid.NativeLib.loadLibAsStream(NativeLib.java:122)
	at org.simgrid.NativeLib.nativeInit(NativeLib.java:58)
	at org.simgrid.NativeLib.nativeInit(NativeLib.java:49)
	at org.simgrid.msg.Msg.<clinit>(Msg.java:82)
	at simulation.Main.main(Main.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

**Comment by mquinson** [comment]
Crap. I'll dig into this, then.
Thx.

**Comment by mfrincu** [comment]
I just tried the one from the website on windows 64 bit for the tutorial next week (from Eclipse). Seems to have the same issue?

Cannot load the bindings to the simgrid library in path NATIVE/Windows/amd64/
Try to install the missing dependencies, which name should appear above.

java.lang.UnsatisfiedLinkError: C:\Users\user\AppData\Local\Temp\simgrid-java5582066171237336713\libsimgrid.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.simgrid.NativeLib.loadLib(NativeLib.java:130)
	at org.simgrid.NativeLib.nativeInit(NativeLib.java:34)
	at org.simgrid.NativeLib.nativeInit(NativeLib.java:26)
	at org.simgrid.msg.Msg.<clinit>(Msg.java:86)
	at cloud.Cloud.main(Cloud.java:20)

**Comment by mquinson** [comment]
The approved source of Windows jar files is appveyor. But unfortunately, it is currently broken, so I cannot propose you to download the most recent jar to test again. I'll try to fix appveyor very soon.

**Comment by mquinson** [comment]
@mfrincu could you please test this jar file and  report whether it works for you?
https://ci.appveyor.com/project/mquinson/simgrid/build/1629/artifacts
Thanks in advance,

**Comment by mquinson** [comment]
this is now fixed.
