### ISSUE TITLE
Random platform generation should be readded at some point

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#60]
I just killed the old C thing for platform generation. It was not tested, not documented, and somehow hard to use. It should be properly redone in lua at some point in the future.

For the record, the commit killing it is 6d29c09ea1d296d6a387aedf84b1c0c7084fbbea

**Comment by agiersch** [comment]
The Lua bindings are dying. The future is C++ ;)

**Comment by randomstuff** [comment]
The future is Python :)

**Comment by mquinson** [comment]
I'm tempted to close this issue because users may be able to do their own platform generator using the C++ platform creation interface. 

The work on Simulacrum was interesting in this context and it is still missing, but I'm not entirely sure that simulacrum was 100% perfect either. It may give a false sense of security and still produce meaningless platforms. 

I'm not sure of what to do here. @frs69wq do you have an opinion?
