### ISSUE TITLE
Processes with the same mailbox have problem when receiving with irecv

### ISSUE THREAD

**Issue by kenenbek** [simgrid/simgrid#76]
I use this code
```
for (int j=0; j<2; j++){
	Process process = new Process(getHost().getName(), "Tier1_2_" + j) {
		@Override
		public void main(String[] strings) throws MsgException {
			while (true){
				commReceived = Task.irecv("Tier1_2");
				commReceived.waitCompletion();
				if (commReceived.test()){
					Task task = commReceived.getTask();
					Msg.info("Receive " + task.getName());
					}
			}
		}
	};process.start();
}
```
So I have two processes with the same mailbox. I send with `isend` to them **one** task. But this task can't reach one of these mailboxes. I expected that this task would be served on the basis "first in - first served". 
```
[100.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-ubuntu-trusty-64/build/SimGrid-3.13/src/simix/smx_global.cpp:554: [simix_kernel/CRITICAL] Oops ! Deadlock or code not perfectly clean.
```
When I send **two** tasks to two processes (even number of tasks to even number of processes) with the same mailbox, all works fine, except the names of task:
```
[Tier1_2:Tier1_2_1:(6) 2.164948] [jmsg/INFO] Receive Task1
[Tier1_2:Tier1_2_0:(5) 2.164948] [jmsg/INFO] Receive Task1
```
When I use "dsend" instead of "isend" all works as expected.

**Comment by mquinson** [comment]
Hello, sorry for the delay.

I need a working example to understand what's going on. I need the full code of all process classes, as well as the platform and deployment files, please.

Thanks,

**Comment by mquinson** [comment]
Hello,

if you don't provide a MWE, we cannot work on the issue. If you think that this issue should be closed, please say so.

Thanks,
