### ISSUE TITLE
SimDag ignores communication cost when number of hosts is greater than 10 

### ISSUE THREAD

**Issue by aliomarabdelazim** [simgrid/simgrid#81]
I developing a code to test dynamic loop scheduling techniques, and I defined my platform as hosts ..not clusters or cabinets, and defined all the routing needed. when the number of hosts is greater than 10, end to end communication tasks execution time is around zero, no matter how big the amount of communication or how slow is the link 

--> platform file 

<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
<config id="General">
<prop id="maxmin/precision" value="0.000000001"></prop>
</config>
<AS id="main" routing="Full">
<link sharing_policy="SHARED" bandwidth="5Mbps" latency="2us" id="link1" state="ON"></link>

<host core="1" pstate="0.0" id="host 0" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 1" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 2" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 3" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 4" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 5" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 6" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 7" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 8" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 9" speed="1562kf"	availability="1.0" state="ON"></host>
<host core="1" pstate="0.0" id="host 10" speed="1562kf"	availability="1.0" state="ON"></host>

<route src="host 1" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 2" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 3" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 4" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 5" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 6" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 7" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 8" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 9" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>
<route src="host 10" dst="host 0"><link_ctn id="link1" direction="NONE"></link_ctn></route>

</AS>
</platform>

**Comment by frs69wq** [comment]
It seems that your message has been cut out. Could you please complete it to help us diagnosing the issue you face?

**Comment by aliomarabdelazim** [comment]
I tried to put the platform file on the topic, but it keeps cutting the xml out, so I compressed the file 
[RP3_platform_generated.xml.zip](https://github.com/simgrid/simgrid/files/300119/RP3_platform_generated.xml.zip)

**Comment by frs69wq** [comment]
Your platform is then 10 hosts (from host1 to host10) connected through a single shared link (latency of 2 microseconds and bandwidth of 5Mb/s) to host0. I don't see anything suspect here, even though this file could be simplified.

For instance hosts could simply be delcared as:
<host id="host 0" speed="1562kf"/>
the other attributes use their default values.
For the routes, you can avoid the direction=NONE

This said, You have to be more specific on your issue. What is the behavior with less than 10 hosts as you said the problem occurs for more than 10. If you could provide a minimal working example that reproduces your issue, it would be fine.

**Comment by aliomarabdelazim** [comment]
[Archive.zip](https://github.com/simgrid/simgrid/files/300192/Archive.zip)
I have made a small example, if you try to run it with platform file contains 10 or  more hosts, you will see that the end to end communication tasks start and finish time is exactly the same, but if you just removed 4 hosts from the platform file, and run the same executable, you will find that the execution time form communication tasks is calculated correctly

**Comment by frs69wq** [comment]
I found the origin of the issue, and SimDag should have raised some warnings (and soon will, thanks to you). Let me explain.
In your platform file you do not define all the routes between each pair of hosts but only from "host 0" to and from every other host.
Then in your simulator you schedule the "master" on hosts[0] (the fist host in the array returned by  sg_host_list()) which unfortunately IS NOT "host 0" but "host 10".
If you look at the output of you minimal example, you'll see that only the communication between "host 10" and "host 0" takes time. All the others are scheduled on undefined routes and take no time (ok, there, SimDag should yell at you).
If I replace "host 0" by "host 10" (and "host 10" by "host 0"), all the communications take the same time.  Another option is to get the host where you schedule the dummy tasks by its name to avoid any surprise:
```
//schedule dummy task on master
SD_task_schedulel(dummy_task,1,sg_host_by_name("host 0"));
```

**Comment by aliomarabdelazim** [comment]
Thank you very much, this was very helpful
