### ISSUE TITLE
libunwind linking problem; unable to build

### ISSUE THREAD

**Issue by sbjoshi** [simgrid/simgrid#88]
Hello,
I am unable to build Simgrid 3.13 from source. 
I used `ccmake .` and enabled model checking feature of simgrid.
Make fails with a linker error 

---------------
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libunwind-ptrace.a(_UPT_access_fpreg.o): relocation R_X86_64_32S against `_UPT_reg_offset' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libunwind-ptrace.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libsimgrid.so.3.13] Error 1
make[1]: *** [CMakeFiles/simgrid.dir/all] Error 2
make: *** [all] Error 2

---------------
I would appreciate any help on this.

**Comment by mquinson** [comment]
This sounds like an error in your package: it seems to me that libunwind-ptrace is not usable from a dynamic library. You may want to try a manual compilation of the library, just to see.

Or maybe @randomstuff has a better idea?

**Comment by randomstuff** [comment]
Yes, for some reason. The linker is trying to link `libsimgrid.so` against non-PIC static libraries (`.a`) of libunwind instead of using dynamic ones (`.so`). On x86_64, including non-PIC code into a `.so` lead to this kind of relocations errors. The expected behaviour is to link against libunwind `.so` files. 

Where did you get libunwind? From your distro (which one)? Is there any `.so` files avaialable?

**Comment by sbjoshi** [comment]
Dear Gabriel,
              Thanks for a quick reply. I got unwind from fedora
repositories. Fedora version 20. The repositories provided libunwind.so.8
and libunwind.so.8.0.1. I do not have control over upgrading the version of
the distro itself (e.g., moving from Fedora 20 to 24).
If sources are available, I can compile in my user directory itself.

Regards,
Saurabh

On Wed, Jun 22, 2016 at 4:40 AM, Gabriel Corona <notifications@github.com>
wrote:

> Yes, for some reason. The linker is trying to link libsimgrid.so against
> non-PIC static libraries (.a) of libunwind instead of using dynamic ones (
> .so). On x86_64, including non-PIC code into a .so lead to this kind of
> relocations errors. The expected behaviour is to link against libunwind
> .so files.
>
> Where did you get libunwind? From your distro (which one)? Is there any
> .so files avaialable?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/simgrid/simgrid/issues/88#issuecomment-227599390>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE2J2YEcTv7X5TrOJ8zMfi1zQ_Fmv0YOks5qOG9ugaJpZM4I6qZC>
> .
>



-- 
---------------------
Saurabh Joshi
---------------------

**Comment by randomstuff** [comment]
Do you have a `libsimgrid-ptrace.so` as well? Could you `find /usr/lib | grep libunwind` ?

**Comment by randomstuff** [comment]
Apparently, there is no `libunwind-ptrace.so` in fedora 20 (only `.a`). So you have to compile it yourself.

**Comment by adegomme** [comment]
We had a fedora 20 builder up until recently, and yes we had to compile libunwind from scratch on this platform.
Download and extract http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz 
and then configure; make; make install should work.

**Comment by sbjoshi** [comment]
Dear All,
             Thanks for your help. Installing libunwind via souce and
linking it with Simgrid-3.13 (by adding a line at the top in
tools/cmake/MakeLib.cmake) worked.
The line that was added was
link_directories(/absolute/path/of/libunwind/toplevel/install/dir)

My colleague Vojtech pointed it out.

This issue can be closed now, thanks for everyone's help.
Regards,
Saurabh

On Wed, Jun 22, 2016 at 3:57 PM, adegomme <notifications@github.com> wrote:

> We had a fedora 20 builder up until recently, and yes we had to compile
> libunwind from scratch on this platform.
> Download and extract
> http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
> and then configure; make; make install should work.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/simgrid/simgrid/issues/88#issuecomment-227704602>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE2J2REQaJOZw-T7tP96LOtNl3Xfvaq7ks5qOQ4SgaJpZM4I6qZC>
> .
>



-- 
---------------------
Saurabh Joshi
---------------------

**Comment by mquinson** [comment]
Thanks for reporting, then.
