### ISSUE TITLE
unexpected behaviors when running SimDag simulation  

### ISSUE THREAD

**Issue by aliomarabdelazim** [simgrid/simgrid#91]
Hello, 
I am simulating batch scheduling algorithms of jobs on SimDag, but when I run the simulation, the output is sometimes correct, sometimes the simulator just hangs, mostly the simulation finishes with a very big number (like there was an overflow somewhere), sometimes it make an exception "too many constrains " in lmm_expand.

I attached the whole the code and you can run: ./simulator platform_generated.xml 240  hpc2n.swf  20 1
 to just read and simulate 20 jobs 

thank you in advance, I really appreciate any help.
[Batch_Scheduling.zip](https://github.com/simgrid/simgrid/files/333069/Batch_Scheduling.zip)

**Comment by frs69wq** [comment]
I just had a look at your code, and found a couple of issues. When I run 
your code with the provided command line, the simulated clock increases 
a lot, up to a point when it's just off limits. It seems to me that it 
comes from the way you handle the wait time (by creating dummy tasks). 
If I comment this line, the execution goes to its end, even though I 
didn't check the timings:

/* if ((scheduledJobs<num_jobs) && sg_host_is_all_idle(hosts,NHOSTS)) */

More precisely, the problem might come from this 
sg_host_is_all_idle(hosts,NHOSTS). When a dummy task is running on 
host[0], there might be no ready tasks (the actual jobs) while all the 
hosts are not idle.

Another issue is that you call SD_simulate while no task is actually 
scheduled which raises SimDag warnings.

By the way, what you are doing really looks like to the SimBatch project:

svn co svn://scm.gforge.inria.fr/svn/simgrid/contrib/trunk/Simbatch

Maybe you should want to have a look at it. The associate research 
report is here https://hal.inria.fr/inria-00115880



Le 25/06/2016 15:23, aliomarabdelazim a écrit :
>
> Hello,
> I am simulating batch scheduling algorithms of jobs on SimDag, but 
> when I run the simulation, the output is sometimes correct, sometimes 
> the simulator just hangs, mostly the simulation finishes with a very 
> big number (like there was an overflow somewhere), sometimes it make 
> an exception "too many constrains " in lmm_expand.
>
> I attached the whole the code and you can run: ./simulator 
> platform_generated.xml 240 hpc2n.swf 20 1
> to just read and simulate 20 jobs
>
> thank you in advance, I really appreciate any help.
> Batch_Scheduling.zip 
> <https://github.com/simgrid/simgrid/files/333069/Batch_Scheduling.zip>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/simgrid/simgrid/issues/91>, or mute the thread 
> <https://github.com/notifications/unsubscribe/ACatOHm2tPJis7fbZbzu9BZoe56KdcKwks5qPSvEgaJpZM4I-V_s>.
>

-- 
One should, for example, be able to see that things are hopeless
and yet be determined to make them otherwise.
                                           -- F. Scott Fitzgerald

**Comment by aliomarabdelazim** [comment]
Thank you very much for your reply, Actually dummy tasks is not the problem, when you remove dummy tasks the simulation just ends after executing first 3 jobs without crashing because the simulation does not run for enough time. but I found that the main issue that causes the clock to increase so fast is in the scheduling function “SD_task_schedule” , in the code I attached before I was creating an array of doubles for flops amount and for bytes amount,

the current fix now is that I put SD_SCHED_NO_COST as bytes amount, and it works fine,
SD_task_schedule(task,workstation_nb,workstation_list,flops_amount_list,SD_SCHED_NO_COST,rate);

If I replaced this constant with an array of doubles containing any values or zeros, I get the unexpected behavior again.

Thank you for sharing the SimBatch project with me, I certainly will look at it, and waiting for your reply further on SD_task_schedule problem


On 28 Jun 2016, at 13:41, Frederic Suter <notifications@github.com<mailto:notifications@github.com>> wrote:

I just had a look at your code, and found a couple of issues. When I run
your code with the provided command line, the simulated clock increases
a lot, up to a point when it's just off limits. It seems to me that it
comes from the way you handle the wait time (by creating dummy tasks).
If I comment this line, the execution goes to its end, even though I
didn't check the timings:

/* if ((scheduledJobs<num_jobs) && sg_host_is_all_idle(hosts,NHOSTS)) */

More precisely, the problem might come from this
sg_host_is_all_idle(hosts,NHOSTS). When a dummy task is running on
host[0], there might be no ready tasks (the actual jobs) while all the
hosts are not idle.

Another issue is that you call SD_simulate while no task is actually
scheduled which raises SimDag warnings.

By the way, what you are doing really looks like to the SimBatch project:

svn co svn://scm.gforge.inria.fr/svn/simgrid/contrib/trunk/Simbatch

Maybe you should want to have a look at it. The associate research
report is here https://hal.inria.fr/inria-00115880



Le 25/06/2016 15:23, aliomarabdelazim a écrit :
>
> Hello,
> I am simulating batch scheduling algorithms of jobs on SimDag, but
> when I run the simulation, the output is sometimes correct, sometimes
> the simulator just hangs, mostly the simulation finishes with a very
> big number (like there was an overflow somewhere), sometimes it make
> an exception "too many constrains " in lmm_expand.
>
> I attached the whole the code and you can run: ./simulator
> platform_generated.xml 240 hpc2n.swf 20 1
> to just read and simulate 20 jobs
>
> thank you in advance, I really appreciate any help.
> Batch_Scheduling.zip
> <https://github.com/simgrid/simgrid/files/333069/Batch_Scheduling.zip>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/simgrid/simgrid/issues/91>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACatOHm2tPJis7fbZbzu9BZoe56KdcKwks5qPSvEgaJpZM4I-V_s>.
>

--
One should, for example, be able to see that things are hopeless
and yet be determined to make them otherwise.
-- F. Scott Fitzgerald

**Comment by frs69wq** [comment]
Well, I tried to remove the dummy tasks too. the simulation stops after 
3 tasks, because for the kernel there is no more runnable tasks.
When I commented /* && sg_host_is_all_idle(hosts,NHOSTS)) */, all the 
jobs are simulated and the simulated doesn't crash either, hence my guess.

About byte amounts, one thing is that it should represent a 
communication matrix, then of size workstation_nb*workstation_nb. 
Another thing is if you have both computation and computations, the 
underlying model will interleave computations and communications at a 
very fine grain. Then all the communications are simulated on the ONLY 
link declared in your platform with its (small) bandwidth of 10,000 bits 
per second (i.e., 1,250 bytes per second). The SD_SCHED_NO_COST allows 
to give a NULL pointer instead when your task is only computation or 
communication.

But again, from what I saw running your code is that dummy tasks seem to 
be created forever ... or a least until the clock reaches an 
unbelievable value.


Le 29/06/2016 14:47, aliomarabdelazim a écrit :
> Thank you very much for your reply, Actually dummy tasks is not the 
> problem, when you remove dummy tasks the simulation just ends after 
> executing first 3 jobs without crashing because the simulation does 
> not run for enough time. but I found that the main issue that causes 
> the clock to increase so fast is in the scheduling function 
> “SD_task_schedule” , in the code I attached before I was creating an 
> array of doubles for flops amount and for bytes amount,
>
> the current fix now is that I put SD_SCHED_NO_COST as bytes amount, 
> and it works fine,
> SD_task_schedule(task,workstation_nb,workstation_list,flops_amount_list,SD_SCHED_NO_COST,rate); 
>
>
> If I replaced this constant with an array of doubles containing any 
> values or zeros, I get the unexpected behavior again.
>
> Thank you for sharing the SimBatch project with me, I certainly will 
> look at it, and waiting for your reply further on SD_task_schedule 
> problem
>
>
> On 28 Jun 2016, at 13:41, Frederic Suter 
> <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> I just had a look at your code, and found a couple of issues. When I run
> your code with the provided command line, the simulated clock increases
> a lot, up to a point when it's just off limits. It seems to me that it
> comes from the way you handle the wait time (by creating dummy tasks).
> If I comment this line, the execution goes to its end, even though I
> didn't check the timings:
>
> /* if ((scheduledJobs<num_jobs) && sg_host_is_all_idle(hosts,NHOSTS)) */
>
> More precisely, the problem might come from this
> sg_host_is_all_idle(hosts,NHOSTS). When a dummy task is running on
> host[0], there might be no ready tasks (the actual jobs) while all the
> hosts are not idle.
>
> Another issue is that you call SD_simulate while no task is actually
> scheduled which raises SimDag warnings.
>
> By the way, what you are doing really looks like to the SimBatch project:
>
> svn co svn://scm.gforge.inria.fr/svn/simgrid/contrib/trunk/Simbatch
>
> Maybe you should want to have a look at it. The associate research
> report is here https://hal.inria.fr/inria-00115880
>
>
>
> Le 25/06/2016 15:23, aliomarabdelazim a écrit :
> >
> > Hello,
> > I am simulating batch scheduling algorithms of jobs on SimDag, but
> > when I run the simulation, the output is sometimes correct, sometimes
> > the simulator just hangs, mostly the simulation finishes with a very
> > big number (like there was an overflow somewhere), sometimes it make
> > an exception "too many constrains " in lmm_expand.
> >
> > I attached the whole the code and you can run: ./simulator
> > platform_generated.xml 240 hpc2n.swf 20 1
> > to just read and simulate 20 jobs
> >
> > thank you in advance, I really appreciate any help.
> > Batch_Scheduling.zip
> > <https://github.com/simgrid/simgrid/files/333069/Batch_Scheduling.zip>
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/simgrid/simgrid/issues/91>, or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/ACatOHm2tPJis7fbZbzu9BZoe56KdcKwks5qPSvEgaJpZM4I-V_s>.
> >
>
> -- 
> One should, for example, be able to see that things are hopeless
> and yet be determined to make them otherwise.
> -- F. Scott Fitzgerald
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on 
> GitHub<https://github.com/simgrid/simgrid/issues/91#issuecomment-229025284>, 
> or mute the 
> thread<https://github.com/notifications/unsubscribe/AQmtjRbBXtSqKEXIh35Cd9iwYmmqKkeRks5qQQh3gaJpZM4I-V_s>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/simgrid/simgrid/issues/91#issuecomment-229345258>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACatONqix0HE_EYkrQ9R_z81wqMwhex-ks5qQmldgaJpZM4I-V_s>.
>

-- 
One should, for example, be able to see that things are hopeless
and yet be determined to make them otherwise.
                                           -- F. Scott Fitzgerald

**Comment by aliomarabdelazim** [comment]
"About byte amounts, one thing is that it should represent a
communication matrix, then of size workstation_nb*workstation_nb." This explains everything, because because in my code, bytes amount was defined as an array of doubles of length workstation_nb, and hence when the simulator is working,  sometimes it can reach unallocated/uninitialized  memory and hence the unexpected behavior.
I fixed it now and everything works fine, but I would suggest that this information be clarified in the documentation, and also it would have been helpful it there were warnings on the array sizes.

and for dummy_task , I also suspected that this may be the source of the problem and implemented another version of the code that do not use dummy_task to handle waits, but it did not help because the code still have the same unexpected behavior (one execution may run fine, other may fail) ... I can share it with you to reproduce the problem if you want.

Many thanks for clarifying this to me

**Comment by frs69wq** [comment]
I just mentioned what flops_amount and bytes_amount parameters of SD_task_schedule should be in the documentation of this function.

**Comment by mquinson** [comment]
I think that this issue was fixed by 1ee20bd190694fd665b8a19b0620362758674aa3

@aliomarabdelazim do you confirm? Can we close the issue now that the doc was updated? Or what is still missing?

Thanks for your help,

**Comment by aliomarabdelazim** [comment]
Thank you very much for your responses and your help. I think the documentation is much clearer now, I would suggest if possible that the functions check for correct array sizes and raise warnings when it is not what the function expects. But as for this issue it can be closed

**Comment by mquinson** [comment]
Unfortunately, it is not possible to check the array sizes because these are C arrays: we don't know their size...

Thanks for your feedback; I'm closing this issue now. Feel free to reopen if you feel so.

**Comment by aliomarabdelazim** [comment]
double array[length];

you can use "sizeof(array)/sizeof(double)" to check the size of double array in C, and so on for other types

Best regards,
Ali

On 04 Jul 2016, at 00:07, Martin Quinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately, it is not possible to check the array sizes because these are C arrays: we don't know their size...

Thanks for your feedback; I'm closing this issue now. Feel free to reopen if you feel so.

**Comment by aliomarabdelazim** [comment]
Sorry, you were correct, this won’t work on arrays in arguments




On 04 Jul 2016, at 00:07, Martin Quinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately, it is not possible to check the array sizes because these are C arrays: we don't know their size...

Thanks for your feedback; I'm closing this issue now. Feel free to reopen if you feel so.
