### ISSUE TITLE
simgrid should not eat --help

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#93]
Hello,

Currently, when running an application using simgrid, passing --help to the application shows the help of simgrid only. Simgrid should see --help and print its help, but not eat it and just continue normally, so that the application can see --help and print its help too before exitting.

Samuel

**Comment by mquinson** [comment]
I fully understand why you'd need that in StarPU, but letting the execution proceed when --help is provided will be strange for other people. Would it be OK if i provide a on_help() signal in which you could register your own function, that'd be executed after our help display and before stopping the execution ?
Of course, I understand that I need to provide a C compatible version of the thing ;)

**Comment by sthibaul** [comment]
Well, the issue is that it's not StarPU which parses "--help", but the application using StarPU. I would rather need a function which allows to tell simgrid not to exit on --help, so that the application's parsing of --help can run too.

**Comment by mquinson** [comment]
ok, that makes sense too. I'll do so.

**Comment by mquinson** [comment]
ok, that makes sense too. I'll do so. 
Note to self, the function could be called `sg_config_continue_on_help()` or something
